### ISSUE TITLE
Harmonize and simplify person employment information

### ISSUE THREAD

**Issue by cdmgtri** [NIEM/NIEM-Releases#105]
It is currently necessary to use an association to specify common information about a person, like employer or job title.  This was done in order to model it as a many-many relationship (one person could have multiple employers, one employer could have multiple employees).  However, the primary use case for NIEM seems to be to capture employment information about a person, so this could be remodeled to make this much easier to do.

Suggest refactoring the person employment association into a regular type, and adding to nc:PersonType as nc:PersonCurrentEmployment and nc:PersonPreviousEmployment.  Also suggest choosing a consistent class term for these properties - "Employment".

Note: There are some additional employment-related properties in NIEM.  Will need some additional harmonization if these changes are recommended.

## Current

**nc:PersonEmploymentAssociationType**

- nc:Employee
- nc:Employer
- nc:EmployeeDepartmentName
- nc:EmployeePositionName
- nc:EmployeeOccupationAbstract
- nc:EmployeeOccupationCategoryAbstract
- nc:EmployeeRankText
- nc:EmployeeIdentification
- nc:EmploymentContactInformation
- nc:EmploymentLocation
- nc:EmployeeShiftText
- nc:EmployeeEarningsRateText
- nc:EmploymentStatus
- nc:EmployeeSupervisor

**im:PersonEmploymentAssociationAugmentationType**

- im:EmploymentAuthorizationEndDate
- im:EmploymentAuthorizationStartDate
- im:EmploymentAuthorizationText
- j:EmploymentAssignedUnitAbstract
- im:EmploymentAuthorizationIndicator

**j:PersonEmploymentAssociationAugmentationType**

- j:EmployeeHoursText
- j:PersonEmploymentAuthorizedEndDate
- j:PersonEmploymentBondPostedToGainEmploymentIndicator
- j:PersonEmploymentDuration
- j:PersonEmploymentEmployeeOccupationTitleText
- j:PersonEmploymentEmployerJobReferenceAbstract
- j:PersonEmploymentEmployerTestimonialText
- j:PersonEmploymentEndReasonText
- j:PersonEmploymentFacility
- j:PersonEmploymentFullTimeIndicator
- j:PersonEmploymentIncludesCommunityServiceIndicator
- j:PersonEmploymentNumberOfDaysEmployedNumeric
- j:PersonEmploymentPlan
- j:PersonEmploymentSupervisor
- j:PersonEmploymentUnemploymentStatusAbstract

**scr:PersonEmploymentAssociationAugmentationType**

- nc:Person
- nc:Organization
- scr:PayRateAmount
- scr:BeginSalaryAmount
- scr:EndSalaryAmount
- scr:EmployeeStarNumberID
- scr:EmployeeBadgeNumberID
- scr:EmployeeCallNumberID

---

## Proposed

**nc:PersonType**

- nc:PersonCurrentEmployment (nc:EmploymentType) - *new*
- nc:PersonPreviousEmployment (nc:EmploymentType) - *new*
- nc:PersonUnemployment (nc:UnemploymentType) - *new*

**nc:~Person~Employment~Association~Type**

- ~nc:Employee~
- nc:*Employment*Employer ~(nc:EntityType)~ (nc:EmployerType)
- nc:~Employee~*Employment*DepartmentName
- nc:~Employee~*Employment*PositionName
- nc:~Employee~*Employment*OccupationAbstract
- nc:~Employee~*Employment*OccupationCategoryAbstract
- nc:~Employee~*Employment*RankText
- nc:~Employee~*Employment*Identification
- nc:EmploymentContactInformation
- nc:EmploymentLocation
- nc:~Employee~*Employment*ShiftText
- nc:~Employee~*Employment*EarningsRateText
- nc:EmploymentStatus
- nc:~Employee~*Employment*Supervisor

**im:~Person~Employment~Association~AugmentationType**

- im:EmploymentAuthorization (im:AuthorizationType) - *new*
  - im:~Employment~AuthorizationStartDate
  - im:~Employment~AuthorizationEndDate
  - im:~Employment~AuthorizationText
  - im:~Employment~AuthorizationIndicator
- j:EmploymentAssignedUnitAbstract - *Recommend moving to the Justice augmentation*

**j:PersonEmploymentAssociationAugmentationType**

- j:~Employee~*Employment*HoursText
- ~j:PersonEmploymentAuthorizedEndDate~ - *Use the im authorization components*
- j:~Person~EmploymentBondPostedToGainEmploymentIndicator
- j:~Person~EmploymentDuration
- ~j:PersonEmploymentEmployeeOccupationTitleText~ - *Duplicates nc:EmploymentPositionName?*
- j:~Person~EmploymentEmployerJobReferenceAbstract
- j:~Person~EmploymentEmployerTestimonialText
- j:~Person~EmploymentEndReasonText
- j:~Person~EmploymentFacility
- j:~Person~EmploymentFullTimeIndicator
- j:~Person~EmploymentIncludesCommunityServiceIndicator
- j:~Person~EmploymentNumberOfDaysEmployedNumeric
- j:~Person~EmploymentPlan
- j:~Person~EmploymentSupervisor 
  - *The Core supervisor is a person; Justice supervisor is an Entity.
  - Rename this as j:EmploymentSupervisoryOrganization (nc:OrganizationType)?*
- j:PersonEmploymentUnemploymentStatusAbstract - *move to nc:UnemploymentType*
  - j:PersonEmploymentUnemploymentStatusText

**scr:PersonEmploymentAssociationAugmentationType**

- ~nc:Person~
- ~nc:Organization~
- scr:*Employment*PayRateAmount
- scr:*Employment*BeginSalaryAmount
- scr:*Employment*EndSalaryAmount
- scr:~Employee~*Employment*StarNumberID
- scr:~Employee~*Employment*BadgeNumberID
- scr:~Employee~*Employment*CallNumberID

**nc:UnemploymentType** - *new*

- nc:UnemploymentStatusAbstract - *moved from Justice*
  - nc:UnemploymentStatusText
- nc:UnemploymentDate - *new* 
- nc:UnemploymentText - *new*

**nc:EmployerType** (extends nc:EntityType) - *new*

- hs:EmployerFEINID
- hs:EmployerPayrollNumberID
- hs:EmployerStateUnemploymentID

**hs:Employer*Augmentation*Type** ~(extends nc:EntityType)~

- ~hs:EmployerFEINID~ - *Moved to Core*
- hs:EmployerName
- hs:EmployerTribeOwnedIndicator
- ~hs:EmployerPayrollNumberID~ - *Moved to Core*
- ~hs:EmployerStateUnemploymentID~ - *Moved to Core*
- hs:EmployerTribalMemberOwnedIndicator
- hs:EmployerCategoryText

**Comment by cdmgtri** [comment]
The Harmonization Workgroup recommends creating an EmployerType in Core but leaving the employment associations as they are.

**Comment by cdmgtri** [comment]
Feedback on recommendation:

Agreed in principle, but there is work to do here. Some initial thoughts:

### Properties that change over time

Properties such as nc:EmploymentShiftText, nc:EmploymentShiftRatesText can change over time (increment system – job does not change but rate goes up with years of service). Should these properties be in a separate type where the temporal component can be incorporated without having to duplicate the full position tombstone info?

### Pay rate, begin salary, end salary

scr: PersonEmploymentAssociationAugmentationType PayRateAmount, BeginSalaryAmount,EndSalaryAmount should be reviewed as candidates for core and incorporating my previous comment. 

For example, I am a Physical Scientist IV with a status of Full-time and for my position classification and level, there is a published salary table which documents the minimum and maximum salary for class and level, along with the increments to go between them. The execution of pay increments starts on start of employment. The pay table itself also has a temporal component since the min/max salary and increments are adjusted when new contracts are settled.

### Employment status vs full time indicator

nc:EmploymentStatus, j:EmploymentFullTimeIndicator should be reviewed for possible consolidation/clarification. We have the following concepts:

- Actual employee status:
  - Unemployed or Unemployed
- Position time:
  - Permanent
  - Non-Permanent – e.g. fixed term or casual/on demand
  - Contractor
- Working Time:
  - Full-time 
  - Part-Time
- Working hours type:
  - Fixed hours
  - Flexible hours
- Working Schedule Type
  - Fixed schedule
  - Flexible schedule

### Shift vs hours

nc:EmploymentShiftText, j:EmployeeHoursText should be reviewed for possible consolidation

### Employment duration, start and end dates

j:EmploymentDuration, j:EmploymentNumberOfDaysEmployeeNumeric should reviewed with an employment start and end date, which I am not seeing in the proposed updates…

**Comment by DonClysdale** [comment]
I recommend keeping nc:Employer instead of nc:EmploymentEmployer - the word Employment does not qualify Employer in any way.
I recommend keeping a refactored nc:PersonEmploymentAssociationType containing:
nc:Person
nc:Employer
nc:Employment

and the nc:PersonFormerEmploymentAssociation and PersonCurrentEmploymentAssociation (nc:PersonEmploymentAssociationType) elements for backwards compatibility.

**Comment by DonClysdale** [comment]
At ESDC we created a complex employment structure that allowed the record of employment at one employer to be maintained (without repeating the employer) with the history of all assignments (employments with different positions etc. This may be a good discussion about the nature of employment, assignments/promotions and pay/salary raises etc

Employment
      Assignment
           Pay Rate
[PersonEmploymentAssociation.txt](https://github.com/NIEM/NIEM-Releases/files/4430267/PersonEmploymentAssociation.txt)

**Comment by cdmgtri** [comment]
### ESDC XSD snippets 

XSD snippets from the PersonEmploymentAssociation.txt attachment above

*Note: minOccurs="0" maxOccurs="unbounded" removed below for readability.*

### Augmentation for nc:PersonEmploymentAssociationType

```xml
<xs:complexType name="PersonEmploymentAssociationAugmentationType">
  <xs:annotation>
    <xs:documentation>A data type for information about an employment instance.</xs:documentation>
  </xs:annotation>
  <xs:complexContent>
    <xs:extension base="structures:AugmentationType">
      <xs:sequence>
        <xs:element ref="emp:PersonEmploymentReasonText"/>
        <xs:element ref="emp:PersonEmploymentSeasonalIndicator"/>
        <xs:element ref="emp:PersonEmploymentTrainingIndicator"/>
        <xs:element ref="emp:PersonEmploymentScheduleIndicator"/>
        <xs:element ref="emp:PersonEmploymentPensionIndicator"/>
        <xs:element ref="emp:LabourMarketImpactAssementExemption"/>
        <xs:element ref="emp:AdditionalEmployeeCompensationAbstract"/>
        <xs:element ref="emp:EmployerFundedEmployeeBenefit"/>
        <xs:element ref="emp:EmployeeLeaveAbstract"/>
        <xs:element ref="emp:EmployerSignature"/>
        <xs:element ref="emp:PersonEmploymentFullTimeIndicatorReasonText"/>
        <xs:element ref="emp:EmploymentPeriod"/>
        <xs:element ref="nc:DistributionText"/>
        <xs:element ref="emp:IncomeStatusAbstract"/>			
      </xs:sequence>
    </xs:extension>
  </xs:complexContent>
</xs:complexType>

<xs:complexType name="EmploymentPeriodType">
  <xs:annotation>
    <xs:documentation>A data type for employment period.</xs:documentation>
  </xs:annotation>
  <xs:complexContent>
    <xs:extension base="structures:ObjectType">
      <xs:sequence>
        <xs:element ref="emp:EmploymentPeriodAbstract"/>
        <xs:element ref="j:Term"/>
      </xs:sequence>
    </xs:extension>
  </xs:complexContent>
</xs:complexType>
```

### Employee position

```xml
<xs:complexType name="EmployeePositionOrganizationAssociationType">
  <xs:annotation>
    <xs:documentation>A data type for information about a specific employee position.</xs:documentation>
  </xs:annotation>
  <xs:complexContent>
    <xs:extension base="nc:AssociationType">
      <xs:sequence>	
        <xs:element ref="nc:Organization" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="emp:EmployeePosition" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="nc:StatusAbstract" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:extension>
  </xs:complexContent>
</xs:complexType>

<xs:complexType name="EmployeePositionType">
  <xs:annotation>
    <xs:documentation>A data type for information about a specific employee position.</xs:documentation>
  </xs:annotation>
  <xs:complexContent>
    <xs:extension base="structures:ObjectType">
      <xs:sequence>
        <xs:element ref="nc:EmployeePositionName"/>
        <xs:element ref="nc:EmployeeOccupationAbstract"/>
        <xs:element ref="nc:EmployeeOccupationCategoryAbstract"/>
        <xs:element ref="nc:EmploymentLocation"/>
        <xs:element ref="emp:EmployeePositionIdentification"/>
        <xs:element ref="emp:EmployeeSupervisorPositionIdentification"/>
        <xs:element ref="emp:EmployeePositionDutiesText"/>
        <xs:element ref="emp:EmployeePositionRequiredJobSkillsText"/>
        <xs:element ref="emp:EmployeePositionEducationLevelRequiredCode"/>
        <xs:element ref="emp:EmployeePositionEducationRequiredText"/>
        <xs:element ref="emp:EmployeePositionFinancialAccountNumberID"/>
        <xs:element ref="emp:EmployeePositionLanguageEssentialAbstract"/>
        <xs:element ref="emp:EmployeePositionLanguageProficiencyRequiredLevelAbstract"/>
        <xs:element ref="emp:EmployeePositionExclusionAbstract"/>
        <xs:element ref="emp:EmployeePositionEssentialIndicator"/>
        <xs:element ref="emp:EmployeePositionBargainingUnitID"/>		
        <xs:element ref="emp:EmployeePositionSecurityClearanceLevelAbstract"/>
        <xs:element ref="emp:EmployeePositionTemporaryIndicator"/>
      </xs:sequence>
    </xs:extension>
  </xs:complexContent>
</xs:complexType>
```

### Assignment

```xml
<xs:complexType name="PersonEmploymentAssignmentAssociationType">
  <xs:annotation>
    <xs:documentation>A data type for information about a specific assignment within an employment instance.</xs:documentation>
  </xs:annotation>
  <xs:complexContent>
    <xs:extension base="nc:PersonEmploymentAssociationType">
      <xs:sequence>
        <xs:element ref="emp:EmployeePosition"/>
        <xs:element ref="em:RegistrationJurisdictionName"/>
        <xs:element ref="emp:Wages"/>
        <xs:element ref="emp:EmployeeHoursNumericAbstract"/>
        <xs:element ref="emp:WagesOvertimePayScale"/>
        <xs:element ref="emp:PersonEmploymentSupervisorIndicator"/>				
      </xs:sequence>
    </xs:extension>
  </xs:complexContent>
</xs:complexType>
```

**Comment by cdmgtri** [comment]
### Current

**nc:PersonEmploymentAssociationType**

- nc:Employee
- nc:Employer
- nc:EmployeeDepartmentName
- nc:EmployeePositionName
- nc:EmployeeOccupationAbstract 
  - nc:EmployeeOccupationText
  - **bls:EmployeeOccupationCategoryCode** - *Move to nc:EmployeeOccupationCategoryAbstract group*
  - **bls:EmployeeOccupationCode** - *Move to nc:EmployeeOccupationCategoryAbstract group*
  - **bls:EmployeeOccupationGeneralCategoryCode** - *Move to nc:EmployeeOccupationCategoryAbstract group*
  - **bls:EmployeeOccupationSubCategoryCode** - *Move to nc:EmployeeOccupationCategoryAbstract group*
- nc:EmployeeOccupationCategoryAbstract
  - nc:EmployeeOccupationCategoryText
- nc:EmployeeRankText
- nc:EmployeeIdentification
- nc:EmploymentContactInformation
- nc:EmploymentLocation
- nc:EmployeeShiftText
- nc:EmployeeEarningsRateText
- nc:EmploymentStatus
- nc:EmployeeSupervisor

**im:PersonEmploymentAssociationAugmentationType**

- im:EmploymentAuthorizationEndDate
- im:EmploymentAuthorizationStartDate
- im:EmploymentAuthorizationText
- **j:EmploymentAssignedUnitAbstract** - *Move to Core?*
- im:EmploymentAuthorizationIndicator

**j:PersonEmploymentAssociationAugmentationType**

- **j:EmployeeHoursText** - *Move to Core, rename as nc:EmployeeWeeklyHoursQuantity*
- j:PersonEmploymentAuthorizedEndDate
- j:PersonEmploymentBondPostedToGainEmploymentIndicator
- **j:PersonEmploymentDuration** - *Move to Core*
- **j:PersonEmploymentEmployeeOccupationTitleText** - *Remove; duplicates nc:EmployeePositionName*
- j:PersonEmploymentEmployerJobReferenceAbstract
- j:PersonEmploymentEmployerTestimonialText
- j:PersonEmploymentEndReasonText
- **j:PersonEmploymentFacility** - *Move to Core*
- **j:PersonEmploymentFullTimeIndicator** - *Move to Core*
- j:PersonEmploymentIncludesCommunityServiceIndicator
- j:PersonEmploymentNumberOfDaysEmployedNumeric
- j:PersonEmploymentPlan
- **j:PersonEmploymentSupervisor** - *uses nc:EntityType vs nc:EmployeeSupervisor (nc:PersonType)*
- **j:PersonEmploymentUnemploymentStatusAbstract** - Move to nc:PersonType?

**scr:PersonEmploymentAssociationAugmentationType**

- **nc:Person** - *Remove; duplicates nc:Employee*
- **nc:Organization** - *Remove; duplicates nc:Employer*
- **scr:PayRateAmount** - *Remove?; similar to nc:EmployeeEarningsRateText*
- **scr:BeginSalaryAmount** - *Move to Core*
- **scr:EndSalaryAmount** - *Move to Core*
- scr:EmployeeStarNumberID
- scr:EmployeeBadgeNumberID
- scr:EmployeeCallNumberID



### New Proposal

**nc:PersonType**

- **nc:PersonEmployedIndicator** - *from j:PersonEmploymentIndicator in j:PersonAugmentationType*
- **nc:PersonJobTitleText** - *Add a simple field for job title without requiring the association?*
- **nc:PersonUnemploymentStatus** - *from j:PersonEmploymentUnemploymentStatusAbstract*


**nc:PersonEmploymentAssociationType**

- Review class terms (Employee vs Employment)
- Review occupation text vs occupation category vs position name

Note:  nc:AssociationBeginDate and nc:AssociationEndDate are inherited.

- nc:Employee
- nc:Employer
- **nc:EmploymentAssignedUnitAbstract** - *from Immigration aug j:EmploymentAssignedUnitAbstract *
- nc:EmploymentContactInformation
- nc:EmployeeDepartmentName
- **nc:EmploymentFacility** - *from j:PersonEmploymentFacility*
- **nc:EmploymentFullTimeIndicator** - *from j:PersonEmploymentFullTimeIndicator*
- **nc:EmploymentHoursFixedIndicator** - *new*
  - *True if the number of hours that employee works each week is fixed; false if the hours are flexible.*
- **nc:EmployeeHoursText** - *number of weekly hours, from j:EmployeeHoursText; use Quantity instead?*
- **nc:EmploymentHistory** (nc:PersonEmploymentAssociationType) - *new*
  - *Use to document various positions, titles, pay amounts, etc., over time*
- nc:EmployeeIdentification
- **nc:EmploymentLengthAbstract** - *new*
  - **nc:EmploymentLengthDuration** - *from j:PersonEmploymentDuration*
  - **j:EmploymentLengthDaysQuantity** - *from j:PersonEmploymentNumberOfDaysEmployedNumeric* 
- nc:EmploymentLocation
- nc:EmployeeOccupationAbstract
  - nc:EmployeeOccupationText
- nc:EmployeeJOccupationCategoryAbstract
  - nc:EmployeeOccupationCategoryText
  - **bls:EmployeeOccupationCategoryCode** - *moved substitution group*
  - **bls:EmployeeOccupationCode** - *moved substitution group*
  - **bls:EmployeeOccupationGeneralCategoryCode** - *moved substitution group*
  - **bls:EmployeeOccupationSubCategoryCode** - *moved substitution group*
- **nc:EmployeePayHourlyIndicator** - *new*
  - *True if an employee is paid on an hourly basis; false if an employee is salaried.*
- **nc:EmployeePayRateAmount** - *from nc:EmployeeEarningsRateText and scr:PayRateAmount*
- **nc:EmployeePayStartAmount** - *from scr:BeginSalaryAmount*
- **nc:EmployeePayEndAmount** - *from scr:EndSalaryAmount*
- nc:EmployeePositionName
- **nc:EmployeePositionBasisAbstract** - *new*
  - **nc:EmployeePositionBasisText** - *new*
  - **nc:EmployeePositionBasisCode** - *new - (codes: permanent, non-permanent, contractor)*
- nc:EmployeeRankText
- **nc:EmployeeSchedule** (nc:ScheduleType) - *new*
  - *Add ScheduleValidDateRange (nc:DateRangeType) to nc:ScheduleType?*
- **nc:EmployeeScheduleFixedIndicator** - *new*
  - *True if an employee's weekly scheduled hours are fixed; false if the scheduled hours are flexible.*
- nc:EmployeeShiftText
- nc:EmploymentStatus
- nc:EmployeeSupervisor - *person or entity?*



**im:PersonEmploymentAssociationAugmentationType**

- im:EmploymentAuthorizationEndDate
- im:EmploymentAuthorizationStartDate
- im:EmploymentAuthorizationText
- ~j:EmploymentAssignedUnitAbstract~ - *Moved to Core*
- im:EmploymentAuthorizationIndicator

**j:PersonEmploymentAssociationAugmentationType**

*Drop "Person" from the class term*

- ~j:EmployeeHoursText~ - *Moved to Core*
- j:~Person~EmploymentAuthorizedEndDate
- j:~Person~EmploymentBondPostedToGainEmploymentIndicator
- ~j:PersonEmploymentDuration~ - *Moved to Core*
- ~j:PersonEmploymentEmployeeOccupationTitleText~ - *Removed; duplicates nc:EmployeeOccupationText*
- j:~Person~Employment~Employer~JobReferenceAbstract
- j:~Person~Employment~Employer~TestimonialText
- j:~Person~EmploymentEndReasonText
- ~j:PersonEmploymentFacility~ - *Moved to Core*
- ~j:PersonEmploymentFullTimeIndicator~ - *Moved to Core*
- j:~Person~EmploymentIncludesCommunityServiceIndicator
- j:PersonEmploymentNumberOfDaysEmployedNumeric - *Moved to Core substitution group*
- j:~Person~EmploymentPlan
- ~j:PersonEmploymentSupervisor~ - *Removed; duplicates nc:EmployeeSupervisor*
- j:~Person~EmploymentUnemploymentStatusAbstract

**scr:PersonEmploymentAssociationAugmentationType**

- ~nc:Person~
- ~nc:Organization~
- ~scr:PayRateAmount~ - *Moved to Core*
- ~scr:BeginSalaryAmount~ - *Moved to Core*
- ~scr:EndSalaryAmount~ - *Moved to Core*
- scr:EmployeeStarNumberID
- scr:EmployeeBadgeNumberID
- scr:EmployeeCallNumberID

**hs:PersonEmploymentAssociationAugmentationType** - *new*

- hs:EmploymentWages

**Comment by cdmgtri** [comment]
## Proposal

*Work is in progress from 2020-07-14 Harmonization workgroup meeting.*

### EmploymentPositionType

*move existing*

- nc:EmployeePositionName
- nc:EmployeeOccupationAbstract
- nc:EmployeeOccupationCategoryAbstract

*add new*

- EmploymentPositionLocation
- EmploymentPositionIdentification
- **SupervisoryEmploymentPosition** (nc:EmploymentPositionType) - *check GFM*
- **EmploymentPositionSupervisoryPosition** (nc:EmploymentPositionType) - *check GFM*
- EmploymentPositionDutyText
- EmploymentPositionTemporaryIndicator
- EmploymentPositionRequiredJobSkillAbstract
  - EmploymentPositionRequiredJobSkillText
- EmployeePositionRequiredEducationAbstract
  - EmployeePositionRequiredEducationText
- EmployeePositionEssentialLanguage (nc:LanguageType)
