### ISSUE TITLE
nc:DriverLicenseCommercialClassCode deprication of one code.

### ISSUE THREAD

**Issue by mark-aamva** [NIEM/NIEM-Releases#108]
On nc:DriverLicenseCommercialClassCode there are 4 codes.  One is now being deprecated, though we don’t have an end date for it yet.  In the AAMVA dictionaries we are adding a note in the description saying “(class M is being retired as a Commercial Class)”.  I propose similar text be appended to the description of value "M".

**Comment by cdmgtri** [comment]
Thanks!  We'll make this change for 5.0.

**Comment by cdmgtri** [comment]
Updated the definition of aamva:DriverLicenseClassCodeSimpleType code "M".
