### ISSUE TITLE
Refactor software components in Core

### ISSUE THREAD

**Issue by cdmgtri** [NIEM/NIEM-Releases#118]
NIEM currently captures software name and version in nc:SoftwareNameType.  Suggest remodeling a bit to allow for a more reusable type with a broader scope that domains and IEPDs can extend or augment.

### Current

nc:SoftwareNameType (extends nc:TextType)
  - nc:softwareVersionText

### Proposed

nc:SoftwareType (extends nc:ItemType)
  - nc:SoftwareName (nc:TextType)
  - nc:SoftwareVersionText (nc:TextType)
  - nc:SoftwareDescriptionText (nc:TextType)
  - nc:SoftwareAugmentationPoint (abstract)

**Comment by cdmgtri** [comment]
The Harmonization Workgroup recommends the above changes.

**Comment by DonClysdale** [comment]
At ESDC we used a type that was copied from older version of biom:
<xs:complexType name="ApplicationProfileType">
		<xs:annotation>
			<xs:documentation>A data type for an application profile specification that is derived from ANSI/NIST-ITL 1-2011update 2013</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="structures:ObjectType">
				<xs:sequence>
					<xs:element ref="tran:ApplicationProfileOrganizationName" minOccurs="0" maxOccurs="1"/>
					<xs:element ref="tran:ApplicationProfileName" minOccurs="0" maxOccurs="1"/>
					<xs:element ref="tran:ApplicationProfileVersionIdentification" minOccurs="0" maxOccurs="1"/>
					<xs:element ref="tran:ApplicationComponentName" minOccurs="0" maxOccurs="1"/>
					<xs:element ref="tran:ApplicationProfileAugmentationPoint" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

that included the concept of a Component.

Perhaps we can add SoftwareComponent (extends nc:ItemType) with SoftwareComponentAugmentationPoint and have SoftwareType (extends nc:ItemType) with additional elements of SoftwareComponent and SoftwareAugmentationPoint.
If we add nc:ItemVersionID (niem-xs:string same as MapVersionID) to nc:ItemType then:
SoftwareName is already implemented by nc:ItemName
SoftwareVersionText is already implemented by nc:ItemVersionID
SoftwareDescriptionText is already implemented by nc:ItemDescriptionText
SoftwareOwner is already implemented by nc:ItemOwner 

covering all the aspects of Software or application profile specification that is derived from ANSI/NIST-ITL 1-2011update 2013

**Comment by cdmgtri** [comment]
The Harmonization Workgroup also recommends adding nc:SoftwareComponent (nc:SoftwareComponentType extends nc:ItemType) to nc:SoftwareType, with element nc:SoftwareComponentVersionID.

**Comment by cdmgtri** [comment]
Also harmonized with scr:SoftwareDetailType, moving vendor information to the Core type.

Updated for 5.0 beta1.
