### ISSUE TITLE
Change schema character encoding to UTF-8

### ISSUE THREAD

**Issue by cdmgtri** [NIEM/NIEM-Releases#125]
NIEM XML schemas have used US-ASCII as the character encoding from NIEM 3.0 through NIEM 4.2.  Changing the character encoding to UTF-8 for better international support.

**Comment by webb** [comment]
The NTAC has approved this change. 

This issue is realized in the dev-prototype-5.0 branch, e.g., in <https://raw.githubusercontent.com/NIEM/NIEM-Releases/dev-prototype-5.0/xsd/codes/iso_639-3.xsd>

```
      <xs:enumeration value="ane">
        <xs:annotation>
          <xs:documentation>Xârâcùù</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
```

Instead of what's in NIEM 4.2:

```
      <xs:enumeration value="ane">
        <xs:annotation>
          <xs:documentation>X&#xe2;r&#xe2;c&#xf9;&#xf9;</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
```
