### ISSUE TITLE
Refactor NIEM Release file & directory structure for NIEM 5.0

### ISSUE THREAD

**Issue by webb** [NIEM/NIEM-Releases#126]
This has been prototyped in [branch dev-prototype-5.0](https://github.com/NIEM/NIEM-Releases/tree/dev-prototype-5.0).

Goals:
- Expect that a NIEM release will be contextualized in a way that indicates the NIEM version, e.g., a git repository commit, or a directory folder that indicates the NIEM version.
- Ensure that the *diff* of 2 releases of NIEM show changes to content, rather than having that obscured via changes to file names and file paths.
- Incorporate as much complexity as is needed, but no more. Simplify as much as is practical.
- Update file encoding to UTF-8 so that international characters are rendered natively

**Comment by cdmgtri** [comment]
File and directory structure were updated for 5.0-alpha1.
