### ISSUE TITLE
nc:LocationHeightMeasureType should extend nc:LengthMeasureType

### ISSUE THREAD

**Issue by cdmgtri** [NIEM/NIEM-Releases#13]
nc:LocationHeightMeasureType currently extends nc:MeasureType.  It should extend nc:LengthMeasureType for access to the relevant unit codes.

**Comment by cdmgtri** [comment]
Created nc:LocationHeightMeasureAugmentation in Core Supplement 4.0.1 to make element nc:LengthUnitAbstract available to use.

This will be merged into nc:LocationHeightMeasureType in the next major release, NIEM 5.0.

**Comment by p9g** [comment]
Assign labels "4.1" and "Core Supplement"

**Comment by cdmgtri** [comment]
An updated type is provided in NIEM Core Supplement 4.0.1.  This type will be merged into Core in the next major release, NIEM 5.0.
