### ISSUE TITLE
Consider if any characters should not be allowed

### ISSUE THREAD

**Issue by cdmgtri** [NIEM/NIEM-Releases#130]
Consider if there are any characters that should be replaced or removed from definitions and codes.  For example, should non-breaking spaces, which usually display like regular spaces, be allowed in code values?  

Changing the schema encoding from US-ASCII to UTF-8 resolves some of the issues with special characters, but there may still be certain characters that should not be removed or replaced for better formatting and consistency.

**Comment by cdmgtri** [comment]
### Reference

There are several tools / extensions that provide special handling for certain characters, sometimes referred to as "gremlins".

#### Gremlins tracker for Visual Studio Code

This Visual Studio Code extension reveals some characters that can be harmful because they are invisible or look like legitimate ones.

https://marketplace.visualstudio.com/items?itemName=nhoizey.gremlins

Character | Zero-width | Description | Level
--------- | ---------- | ----------- | -----     
"200b" | true  | zero width space | error
"200e" | true | left-to-right mark | error
"202c" | true | pop directional formatting | error
"202d" | true | left-to-right override | error
"202e" | true | right-to-left override | error
"fffc" | true | object replacement character | error
"200c" | true | zero width non-joiner | warning
"201c" | | left double quotation mark | warning
"201d" | | right double quotation mark | warning
"0003" | | end of text | warning
"00a0" | | non breaking space | info

**Comment by webb** [comment]
The NTAC doesn't think that there's a good set of characters that should be prohibited in NIEM schemas by conformance rules. It's much more likely that use of odd characters should be considered an issue of quality, rather than conformance. NTAC recommends creating quality control tests to ensure that characters are as intended.

**Comment by cdmgtri** [comment]
The Harmonization Workgroup recommends checking definitions and code values for special characters, new lines, and tab returns as part of general QA testing.  These characters should not be allowed without a valid reason for inclusion.

**Comment by cdmgtri** [comment]
QA checks have been added for non-breaking spaces, line breaks, and tabs.  Non-breaking spaces will be allowed in certain cases (e.g., country names, language names) but will otherwise be replaced with regular spaces.
