### ISSUE TITLE
Harmonize jurisdiction components

### ISSUE THREAD

**Issue by cdmgtri** [NIEM/NIEM-Releases#141]
Review jurisdiction-related components.

### nc:JurisdictionType

A data type for a geopolitical area in which an organization, person, or object has a specific range of authority.

- nc:JurisdictionAbstract
  - nc:JurisdictionText
  - j:JurisdictionANSID20AuthorityCode
  - mo:AuthorityURI
- nc:AddressCityName
- nc:AddressCountry (nc:CountryType)
- nc:AddressCountyAbstract
- nc:AddressState (nc:StateType)
- nc:JurisdictionIdentification

*Keep separate city / county / state / country elements, or create a new nc:JurisdictionLocation (nc:LocationType) element?*

### j:JurisdictionAugmentationType

- j:JurisdictionDescriptionText
- j:JurisdictionDistrictText - *Could be represented via nc:LocaleDistrictName*
- j:JurisdictionRestrictionText
- j:JurisdictionDistrictIdentification
- j:JurisdictionTitle (j:ItemTitleType) - A title issued by a jurisdiction.
  - *Remove element - title can already be linked to a jurisdiction*

### nc:JurisdictionType

- nc:JurisdictionAbstract
  - nc:JurisdictionText
  - j:JurisdictionANSID20AuthorityCode
  - mo:AuthorityURI
- nc:JurisdictionDescriptionText - *moved from Justice*
- nc:JurisdictionIdentification - *new*
- nc:JurisdictionLocation (nc:LocationType)

### nc:LocaleType

(only new additions shown below)

- nc:LocaleDistrictIdentification 
- nc:LocaleRestrictionText

**Comment by DonClysdale** [comment]
It make sense to create nc:JurisdictionLocation and eliminate the single elements.

That would facilitate folding j:JurisdictionAugmentationType into nc:JurisdictionLocation as well via LocationLocale (nc:LocaleType). There are nc:LocaleDistrictName/nc:LocaleJudicialDistrictName and nc:LocaleDescriptionText and nc:LocaleJudicialDistrictAbstract which could be replaced by (or used to substitute for)  j:JurisdictionDistrictText and j:JurisdictionDescriptionText and j:JurisdictionDistrictIdentification elements respectively. It would make sense to add nc:LocaleRestrictionText as replacement for j:JurisdictionRestrictionText which would eliminate the need for j:JurisdictionAugmentationType.

**Comment by bdhandspicker** [comment]
The notion of defining jurisdiction solely in terms of location has makes me uncomfortable. Jurisdiction is "the extent of the power to make legal decisions and judgments". Sometimes that could be described in terms of a specific place (location) such as a state law enforcement officer having jurisdiction within a specific state. But location for jurisdiction becomes challenging at the very local and the regional/national level. For example, what is the jurisdiction of a town police officer? Sure, they work for the town, but their actual authority is, I believe, given by the state and they have legal jurisdiction in other towns across the state, not just within the town they work for. On the other end of the examplar scale, a federal appeals court's jurisdiction covers a district that crosses multiple states that are tough to nail down as a specific location. (https://en.wikipedia.org/wiki/United_States_courts_of_appeals) So, I think we might be making a mistake trying to shoehorn the jurisdiction concept solely into a location with an address, town, state, etc. The jurisdiction concept is only loosely associated with location and has more to do with abstract political organization than "place on the planet".

**Comment by cdmgtri** [comment]
Those are good points.  We want to make sure we don't end up conflating jurisdiction and location.  But instead of having separate fields in JurisdictionType for county, city, state, country, district, etc., we might be able to create a new element like nc:JurisdictionLocation under nc:JurisdictionType that makes those same fields available, plus many more.  May still need to augment this in some cases if LocationType doesn't have a good way of representing certain kinds of regions.

It seems like we could also do a better job of capturing the jurisdiction authority.  We currently have an AAMVA code set, a URI, and a text field, but I think we could make the substitution group name clearer, and we might add an organization as an additional representation.

Are there other kinds of information we should capture about a jurisdiction besides an ID, location info, and authority?

**Comment by cdmgtri** [comment]
The Harmonization Workgroup recommends the given proposal.
