### ISSUE TITLE
Add new DNA content to the Biometrics domain

### ISSUE THREAD

**Issue by cdmgtri** [NIEM/NIEM-Releases#152]
The Biometrics domain is preparing new DNA content for inclusion with 5.0.

### New properties

DNALocusText
DNAAlleleCall
DNAAllele
DNABatchIdentification
DNALane
DNALocus
DNAAnalysisQuantity
DNATechnologyMatchScore
DNALocusMatchScore
matchStatusCode

### First draft:

[niem-5.0-cr-biom beta 05_27_20.xlsx](https://github.com/NIEM/NIEM-Releases/files/4696877/niem-5.0-cr-biom.beta.05_27_20.xlsx)

**Comment by cdmgtri** [comment]
The Biometrics domain has decided to hold changes for the 5.1 release.

**Comment by krishnaVamsy** [comment]
Hi Christina, Attached contains updated list of DNA attributes for 5.1. Thank you.
[DNA Attributes Planned For NIEM5_1 V8.xlsx](https://github.com/NIEM/NIEM-Releases/files/5789536/DNA.Attributes.Planned.For.NIEM5_1.V8.xlsx)

**Comment by cdmgtri** [comment]
Updates made in 5.1 alpha 1.
