### ISSUE TITLE
CUI feedback

### ISSUE THREAD

**Issue by cchipman6** [NIEM/NIEM-Releases#158]
1.	CUICategoryCodeSimpleType, code CONREG: Please add “Entity Registration Information.” to the front of the definition.
2.	CUICategoryCodeSimpleType: Please add new code “OPSEC” with definition: “Operations Security. Critical information determined to give evidence of the planning and execution of sensitive (frequently classified) government activities after going through a formal systematic vetting process in accordance with National Security Decision Directive Number 298. This process identifies unclassified information that must be protected. It almost always results from an agency’s official OPSEC program, or is otherwise commonly approved for use by the CUI Senior Agency Official.”
3.	CUILimitedDisseminationControlCodeSimpleType, code DELIB: The code includes character string &#10;

**Comment by kstewart83** [comment]
In the `REL TO` documentation block it states:

```
Note: See list of approved country codes for use with REL TO here.
```

Is it intended that the `here` is linked to something? I'm not overly familiar with XSDs or NIEM, but it seems like that was intended to be some time of explicit connection.

**Comment by cchipman6** [comment]
> In the REL TO documentation block it states:
> Note: See list of approved country codes for use with REL TO here.
> 
> Is it intended that the here is linked to something? I'm not overly familiar with XSDs or NIEM, but it seems like that was intended to be some type of explicit connection.

Thank you for the comment. This statement was inadvertently copied from the CUI website and should be deleted from the XSD.

**Comment by kstewart83** [comment]
Is there an intent to semantically bind the list of countries to something like ISO 3166 or something else within the NIEM model?

**Comment by cchipman6** [comment]
> Is there an intent to semantically bind the list of countries to something like ISO 3166 or something else within the NIEM model?
Yes, likely genc:CountryAlpha3CodeType.
