### ISSUE TITLE
Organize GENC codes in the release package more consistently

### ISSUE THREAD

**Issue by cdmgtri** [NIEM/NIEM-Releases#176]
The package layout for GENC is inconsistent with all of the other code set schemas since GENC also includes code lists.  GENC is the only one to have a subfolder under the `xsd/codes` directory.

### Current:

```sh
​xsd/
  codes/
    genc/
      - genc.xsd   # inconsistent with all of the other code schemas
      - genc_geo-division_3-11_char6.csv
      - genc_geo-political_3-11_char2.csv
      - xml-catalog.xml
    - aamva_d20.xsd
    - ag_codes.xsd
```

### Alternative 1

Create a new xsd/code-lists directory just for the CSVs

Option 1:

```sh
​xsd/
  codes/
    - aamva_d20.xsd
    - ag_codes.xsd
    - genc.xsd
  code-lists/
    genc/
      - genc_geo-division_3-11_char6.csv
      - genc_geo-political_3-11_char2.csv
      - xml-catalog.xml
```

### Alternative 2

Inline all of the genc files under `xsd/codes`

```sh
​xsd/
  codes/
    - aamva_d20.xsd
    - ag_codes.xsd
    - genc.xsd
    - genc_geo-division_3-11_char6.csv
    - genc_geo-political_3-11_char2.csv
    - xml-catalog.xml
```

**Comment by webb** [comment]
NTAC proposes:
```
- codes/
   - genc.xsd
   - genc/
      - genc_*.csv
      - xml-catalog.xml
```

It makes subsets more consistent for those omitting the CSV files. It makes it easy to later consistently add CSVs for existing code lists. It's unsurprising and obvious that genc/ contains support stuff for genc.xsd.
