### ISSUE TITLE
geo:EllipseType and mo:WGS84EllipseType are identical

### ISSUE THREAD

**Issue by webb** [NIEM/NIEM-Releases#177]
Two types in NIEM 5.0beta1 are identical: geo:EllipseType and mo:WGS84EllipseType

The mo version could be removed and the geo version substituted.

**Comment by cdmgtri** [comment]
I believe this and some similar MilOps GML adapter types were created to capture some additional semantics in the definitions.  Will review this comment with the MilOps domain to consider for NIEM 5.1.

**Comment by cdmgtri** [comment]
Migrated to niemopen/niem-model#12
