### ISSUE TITLE
cui:SpecifiedCategoryMarkingCode codes do not include "SP-"

### ISSUE THREAD

**Issue by cdmgtri** [NIEM/NIEM-Releases#194]
The vocabulary for cui:SpecifiedCategoryMarkingCode does not put “SP-” in front of the code from the CUI Registry.

*Feedback submitted for RC2 via email*

**Comment by cchipman6** [comment]
Per CUI Program Office: add the prefix "SP-" to the specified category marking codes enumerated in SpecifiedCategoryMarkingCodeSimpleType.

**Comment by cchipman6** [comment]
Per CUI meeting 9Oct20: add the prefix "SP-" to the specified category marking codes enumerated in SpecifiedCategoryMarkingCodeSimpleType.
