### ISSUE TITLE
CUI and GENC codes

### ISSUE THREAD

**Issue by cdmgtri** [NIEM/NIEM-Releases#195]
The U.S. Government agencies are required to use the GENC profile of ISO 3166-1 and not use pure ISO 3166-1.

However, NIEM imports GENC digraphs, trigraphs, and numeric country codes, and subdivision codes.
1. CUI Registry page for Limited Dissemination Controls  indicates trigraphs only should be used (just like in vocabularies for REL TO and DISPLAY ONLY for classified data).
2. It is not allowed to REL TO or DISPLAY ONLY country subdivisions (e.g., provinces).

*Feedback submitted for RC2 via email*

**Comment by cchipman6** [comment]
The NIEM CUI schema currently supports use of 3-character GENC codes only. It does not support use of digraphs, numeric country codes, or subdivision codes. However, per CUI program office: support for additional REL TO and DISPLAY ONLY options (see IC-ISM tetragraphs and NATO pattern) should be added.

**Comment by cchipman6** [comment]
Per CUI meeting 9Oct20: NIEM's CUI RELTO option will include a substitutable property with one substitutable element for GENC country code trigraphs for use with CUI RELTO and DISPLAY ONLY limited dissemination controls.
