### ISSUE TITLE
NIEM CUI is missing tetragraphs

### ISSUE THREAD

**Issue by cdmgtri** [NIEM/NIEM-Releases#196]
NIEM CUI is Missing tetragraphs. 

NIEM's use of ISO 3166-1 country code vocabulary for REL TO marking means it is not possible to REL TO a tetragraph.

1. CUI Registry explicitly includes REL TO international organization tetragraphs (see https://www.archives.gov/cui/registry/limited-dissemination), although the Registry’s pointer to the list of country codes does not include tetragraphs.
2. Recommend that NIEM use the publicly released ISMCAT CVE for tetragraphs (currently only version 2).

*Feedback submitted for RC2 via email*

**Comment by cchipman6** [comment]
Per CUI program office: add IC-ISM tetragraphs and NATO pattern as options for REL TO and DISPLAY ONLY.

**Comment by cchipman6** [comment]
Per CUI meeting 9Oct20: the CAPCO coalition tetragraphs and NATO special words options will NOT be added to the NIEM 5.0 release. They are currently marked FOUO and are undergoing a public release determination, with no estimated approval timeframe. In the mean time for NIEM 5.0, convert the CUI LimitedDisseminationControlRELTOCountryCode property to a substitution group with one substitutable element for GENC country code trigraphs and revise the related data definitions to include both RELTO and DISPLAY ONLY options.
