### ISSUE TITLE
CUI `NATO Unclassified` and `NATO Restricted` codes

### ISSUE THREAD

**Issue by cdmgtri** [NIEM/NIEM-Releases#197]
NIEM includes the following entries in the vocabulary for **cui:BasicCategoryMarkingCode**: `NATO Unclassified` and `NATO Restricted`.

1. These values should be in the vocabulary for **cui:SpecifiedCategoryMarkingCode**.
2. The CUI Registry does not provide a marking for `NATO U` or `NATO R`. Instead, it states “Mark this information in accordance with instructions in the United States Security Authority for NATO, Instruction 1-07 and supporting NATO Security Directives.” Including NATO U and NATO R in the CUI Specified Category vocabulary means a NATO UNCLASSIFIED document in NIEM would have the banner: CUI//SP-NATO UNCLASSIFIED, which is wrong.

*Feedback submitted for RC2 via email*

**Comment by cchipman6** [comment]
Per CUI program office: move "NATO Restricted" and "NATO Unclassified" from BasicCategoryMarkingCodeSimpleType to SpecifiedCategoryMarkingCodeSimpleType, change codes to "SP-NR" and "SP-NU", respectively.

**Comment by cchipman6** [comment]
Per CUI meeting 9Oct20, remove NATO Restricted and NATO Unclassified from list of CUI category codes. CUI working with IC will make a determination whether to re-add them at a later date.
