### ISSUE TITLE
CUI LimitedDissemination 'DISPLAY ONLY'

### ISSUE THREAD

**Issue by cdmgtri** [NIEM/NIEM-Releases#198]
It is unclear that if there is a **cui:LimitedDisseminationControlCode** = `DISPLAY ONLY` then there should be a **cui:LimitedDisseminationControlRELTOCountryCode** value to go with DISPLAY ONLY.

1. Definition of **cui:LimitedDisseminationControlRELTOCountryCode** only documents its use for `REL TO`, when it should also say use it for `DISPLAY ONLY`.
2. ISM enforces through Schematron rules but it appears NIEM does not have rules like that.

*Feedback submitted for RC2 via email*

**Comment by cchipman6** [comment]
Per CUI program office: the data definition and likely the property name will be changed to reflect support for DISPLAY ONLY.

**Comment by cchipman6** [comment]
Per CUI meeting 9Oct20: update definition(s) for CUI "RELTO" property(ies) to include support for DISPLAY ONLY limited dissemination control.
