### ISSUE TITLE
CUI and multiple dissemination controls

### ISSUE THREAD

**Issue by cdmgtri** [NIEM/NIEM-Releases#199]
Structure for dissemination controls is unclear on how to use for multiple dissemination controls, especially with REL TO or DISPLAY ONLY.

*Feedback submitted for RC2 via email*

**Comment by cchipman6** [comment]
Per CUI program office: within LimitedDisseminationControlType, change cardinality of LimitedDisseminationControlCode to maxOccurs="1" to limit to a single limited dissemination control per use of type. In addition, change cardinality of LimitedDisseminationControlDLONLYText to a single occurrence (maxOccurs="1").

**Comment by cchipman6** [comment]
Per CUI meeting 9Oct20: within LimitedDisseminationControlType, change cardinality of LimitedDisseminationControlCode to maxOccurs="1" to limit to a single limited dissemination control per use of type. In addition, change cardinality of LimitedDisseminationControlDLONLYText to a single occurrence (maxOccurs="1").
