### ISSUE TITLE
Release 3.2 Alternative Format Version Issue

### ISSUE THREAD

**Issue by TJKoury** [NIEM/NIEM-Releases#2]
Taking it up here.

Several attributes seem to be incorrect or out of date.

For example, in the edxl-cap.xsd document, the imported namespace for 'cap' is version 1.1, and in the reference documents the path is correct 'external/cap/1.1', however in the .xslx tab Namespace, cap has a Version Release Number of 1.0, making it impossible to programmatically access the correct external schema.

**Comment by cdmgtri** [comment]
This should be fixed as of NIEM 4.0.  Thanks!
