### ISSUE TITLE
NCIC 4th Qtr Code Tables Update for NIEM 4.2 

### ISSUE THREAD

**Issue by baronil** [NIEM/NIEM-Releases#20]
Provided is the updated NCIC codes for the 4th quarter. One of the biggest changes between what is currently in NIEM and the attached updates is the “0” vs “O” (zero vs O).  In the current postings all codes that should have contained “O”. An example would be the code for the color brown. The code uses zero in place of the letter “o”. The tables attached have the “O” were it should be.

Attached is the NEIM/NCIC mapping spreadsheet you requested help with.

[NCIC NIEM 2018 Q4.zip](https://github.com/NIEM/NIEM-Releases/files/2828855/NCIC.NIEM.2018.Q4.zip)
[ncic-niem-mapping_20181106_MissingCorrespondingElements.xlsx](https://github.com/NIEM/NIEM-Releases/files/2828856/ncic-niem-mapping_20181106_MissingCorrespondingElements.xlsx)

**Comment by cdmgtri** [comment]
NCIC codes were updated in the 4.2 alpha release.
