### ISSUE TITLE
EmploymentPayRateAmount should be of type AmountType

### ISSUE THREAD

**Issue by DonClysdale** [NIEM/NIEM-Releases#205]
"nc:EmploymentPayRateAmount" type="nc:TextType"

Should be of type AmountType

**Comment by cdmgtri** [comment]
The element type has been fixed.

In addition after another review of all amount elements, element **it:CustomsValuationAmount** (it:CustomsValuationType) has a complex structure type that does not represent a simple monetary value, so the "Amount" representation term has been removed.
