### ISSUE TITLE
Refactor nc:EmployeeAssignmentAssociation

### ISSUE THREAD

**Issue by DonClysdale** [NIEM/NIEM-Releases#206]
Move nc:nc:EmployeeRegistrationAbstract and nc:EmployeeSupervisorIndicator elements to nc:EmploymentAssociationType so that they can be used as part of EmploymentAssociation and/or the EmployeeAssignmentAssociation. This is consistent with the previous movement of other elements from nc:EmployeeAssignmentAssociationType to nc:EmploymentAssociationType.

**Comment by cdmgtri** [comment]
Migrated to niemopen/niem-model#14
