### ISSUE TITLE
Revert changes to NCIC code lists

### ISSUE THREAD

**Issue by mikehulme** [NIEM/NIEM-Releases#211]
In NIEM 5.0/JXDM 7.0, a number of frequently-used NCIC code lists were changed from the codes used since 1967 and continue to be used in tens of thousands of information systems today.  The code lists were changed to use the literal value as the code – for example, the eye color code for "BROWN" has been BRO for the last 54 years, but now it is BROWN. In addition, these code lists were (inexplicably?) removed from ncic.xsd in the codes folder and are now defined in jxdm.xsd in the domains folder.

This makes NIEM 5.0 more cumbersome to use in law enforcement and criminal justice exchanges that use these NCIC code lists (which are pervasive). An awkward workaround when using NIEM 5.0 (for everything else) is to use JXDM 6.2/FBI_NCIC 4.2 (from NIEM 4.2) for these NCIC code lists. Perhaps there is a better workaround I haven't thought of.

The latest version of FBI NCIC messages, v2, released January 2021, uses NIEM 4.2/JXDM 6.2/FBI_NCIC 4.2. So while the intent of FBI CJIS was to standardize code lists across CJIS programs, NCIC messages used in the NCIC 3rd Generation (N3G) will still continue to use the prevailing code lists.

I recommend a domain update (perhaps even before NIEM 5.1) that:
1. Reverts these code lists back to their original enumeration values and type names.
2. Restores the location of their type definitions to codes/ncic.xsd.
3. Reverts the associated element names to use the original type names.
3. Adds another set of code lists for the "new" NCIC code list values, also defined in codes/ncic.xsd. I don't have a good recommendation for naming these code lists (types and elements) to distinguish them. Perhaps they could have "V2" appended to the property term (e.g., ncic:PersonBloodTypeCodeV2SimpleType and j:PersonBloodTypeCodeV2).

The affected code lists are:
- j:PersonBloodTypeCodeSimpleType
- j:PersonEthnicityCodeSimpleType
- j:PersonEyeColorCodeSimpleType
- j:PersonHairColorCodeSimpleType
- j:PersonNameCategoryCodeSimpleType
- j:PersonRaceCodeSimpleType
- j:PersonSkinToneCodeSimpleType

**Comment by cdmgtri** [comment]
These codes were re-added back to the NCIC namespace in NIEM 5.1 alpha2.

Additionally, a domain update will soon be published for NIEM 5.0, once updates to the SSGT are ready to be deployed.

Thanks!

**Comment by cdmgtri** [comment]
See tag [niem-5.0.1-justice](https://github.com/NIEM/NIEM-Releases/tree/niem-5.0.1-justice) for updated schemas.
