### ISSUE TITLE
NCIC 2019 1st QTR Code Tables Update for NIEM 4.2

### ISSUE THREAD

**Issue by baronil** [NIEM/NIEM-Releases#22]
Attached is a zip file containing the first QTR of NCIC code tables.
[NCIC NIEM 2019 Q1.zip](https://github.com/NIEM/NIEM-Releases/files/3091112/NCIC.NIEM.2019.Q1.zip)

**Comment by cdmgtri** [comment]
Superseded by #63, NCIC 2019 2nd QTR update.
