### ISSUE TITLE
revise geospatial namespace documentation

### ISSUE THREAD

**Issue by iamdrscott** [NIEM/NIEM-Releases#220]
The documentation for the geospatial adapter namespace says it references unmodified local copies of the canonical GML schema documents.  We changed that in NIEM 5.  It now references a subset of the GML schema.

**Comment by cdmgtri** [comment]
Thanks!  Should be able to get that fixed for 5.1.

**Comment by cdmgtri** [comment]
Updated in NIEM 5.1 beta 1.
