### ISSUE TITLE
Add new CUI Limited Dissemination Control RELIDO

### ISSUE THREAD

**Issue by cchipman6** [NIEM/NIEM-Releases#225]
Add the following LDC to both LDC code lists: DocumentMarkingLDCCodeSimpleType and PortionMarkingLDCCodeSimpleType. 

enumeration value: RELIDO
documentation: Releasable by information disclosure official. A permissive foreign disclosure and release marking used on information to indicate that the originator has authorized a Senior Foreign Disclosure and Release Authority (SFDRA) to make further sharing decisions for uncaveated intelligence material (intelligence with no restrictive dissemination controls) in accordance with existing procedures, guidelines, and implementation guidance. Second party integrees (people who work solely under direction and operational control of the Director of the NSA/Chief of Central Security Service on cryptologic or information assurance activities) may access RELIDO information that is not classified military information (CMI) or signals intelligence (SIGINT) without a SFDRA review, including intelligence information created after 28 June 2010 - excluding SIGINT – which carries no foreign disclosure and release markings and hence is treated as if marked RELIDO.
Note: Only agencies that are eligible to use RELIDO in the intelligence community (IC) classified information context may use this LDCM on CUI. It is defined and applied in the same manner as in the IC context.

**Comment by cdmgtri** [comment]
Updated in NIEM 5.1 RC2.
