### ISSUE TITLE
Update code in ucr:IncidentBiasMotivationCodeSimpleType

### ISSUE THREAD

**Issue by cdmgtri** [NIEM/NIEM-Releases#229]
From the FBI:

Under **ucr:IncidentBiasMotivationCodeSimpleType**, needs to change from

CODE: ANTI-MORMON
DESCRIPTION: ANTI-MORMON

to

CODE: ANTI-CHURCH_OF_JESUS_CHRIST
DESCRIPTION: ANTI-CHURCH OF JESUS CHRIST

**Comment by cdmgtri** [comment]
Updated in NIEM 5.1-RC3.

**Comment by Apdlrcjafg19** [comment]
Avance
