### ISSUE TITLE
nc:AssociationType should extend structures:ObjectType instead of structures:AssociationType

### ISSUE THREAD

**Issue by DonClysdale** [NIEM/NIEM-Releases#23]
structures:ObjectType and structures:AssociationType are similar - except for name of AugmentationPoint

When nc:AssociationType is instantiated, it has two elements/properties with the same name:
           nc:AssociationAugmentationPoint and structures:AssociationAugmentationPoint

When object types are used in other tools (e.g. Java) to implement the interface - the two properties with the same name are not allowed.

If nc:AssociationType was extending structures:ObjectType then nc:AssociationAugmentationPoint provides a place to augment nc:AssociationType, there would be no duplicate properties with the same name and structures:AssociationType could be deprecated.

**Comment by cdmgtri** [comment]
Thanks for the feedback!  I'll submit this to the NIEM Technical Architecture Committee (NTAC) so they can consider this for NIEM 5.0.

**Comment by webb** [comment]
1. JAXB can handle schema-defined elements with the same local name, when it's properly configured.
2. structures:AssociationType is a basis for all associations; nc:AssociationType provides additional properties that may be used when needed.
3. If you don't need all the augmentation points, leave them out of your subset.
