### ISSUE TITLE
Update definition of cyber:Platform

### ISSUE THREAD

**Issue by cdmgtri** [NIEM/NIEM-Releases#231]
Both cyber:Platform and cyber:PlatformName have the same definition.  The definition of cyber:Platform should be updated.

**cyber:Platform** (cyber:PlatformType) - A name of an operating system and hardware on which a software application can be run

**cyber:PlatformName** (nc:TexType) - A name of an operating system and hardware on which a software application can be run

**Comment by cdmgtri** [comment]
For **cyber:Platform**, use definition:

An operating system and hardware on which a software application can be run

**Comment by AtesComp** [comment]
Also, for NIEM to play in the Cyber domain, please look at the OASIS Open TAC TC.  It has normalized the CTI TC's STIX taxonomy as an RDF ontology and provides all the standard vocabulary required.

**Comment by cdmgtri** [comment]
Resolved by #233.
