### ISSUE TITLE
5.2 Alpha changes/updates for Cyber Domain

### ISSUE THREAD

**Issue by StaceyWrightCSN** [NIEM/NIEM-Releases#237]
**NEW properties that are part of cyber:MalwareType**
- cyber:RansomwareIndicator (niem-xs:Boolean)  True if the malware is ransomware; False otherwise.
- cyber:MalwareHash (nc:TextType)	A hash value or code; a result of a function to map data of an arbitrary size to a fixed-size .
- cyber:MalwareHASHAlgorithm (nc:TextType) An algorithm used to produce a hash.

**Tweaked definitions:**
- cyber:BackupAvailableCategoryCode    A category code for the type of backup available.
- cyber:IncidentConsequenceRecoverabilityEstimatedDuration   An estimate of the duration to potentially recover from the consequences of the incident.
- cyber:IncidentConsequenceRecoverabilityActualDuration	niem-xs:duration	A duration of the time to potentially recover from the consequences of the incident.

**Properties that were not tied to Type** 
- cyber:CompromisedDevice should be under cyber:CyberIncidentType
- cyber:CyberIndicatorPatternDefensiveMeasureCode should be under cyber:CyberIndicatorPatternType 
- REMOVE cyber:ResponderEntity
- cyber:VulnerabilityWidespreadCode should be under cyber:CyberVulnerabilityType

**Comment by cdmgtri** [comment]
Updated in NIEM 5.2.
