### ISSUE TITLE
Add new nc:PersonContactInformation element to nc:PersonType

### ISSUE THREAD

**Issue by cdmgtri** [NIEM/NIEM-Releases#29]
nc:PersonType has ways to represent home, work, and emergency contact information.  Need to add a generic element for contact info in case the type isn't known.  Suggest adding this to a Core Supplement for the 4.2 release.

---

**Current:**

**nc:PersonHomeContactInformation** (nc:ContactInformationType) 

A means of contacting a person at home.

**nc:PersonEmergencyContactInformation** (nc:ContactInformationType) 

A means of contacting someone in the event of an emergency.

**nc:EmploymentContactInformation** (nc:ContactInformationType) 

A means of contacting a person at work.
 
---

**Proposed addition:**

**nc:PersonContactInformation** (nc:ContactInformationType)

A means of contacting a person.

**Comment by DonClysdale** [comment]
I would like to see this newly added nc:PersonContactInformation be the substitution head for all the nc:PersonXXXContactInformation elements which will reduce the nc:PersonType "sprawl". It would be cleaner to have only one nc:ContactInformationType element, nc:PersonContactInformation assign all the other nc:PersonXXXContactInformation elements to that substitutionGroup and remove them from nc:PersonType.

**Comment by cdmgtri** [comment]
Moving issue to the 5.0 project since we did not get approval in time for 4.2.

See issue #75 for the substitution group recommendation.

**Comment by cdmgtri** [comment]
The Harmonization Workgroup recommends adding the new element nc:PersonContactInformation.

**Comment by cdmgtri** [comment]
Approved by the NBAC at the annual meeting.
