### ISSUE TITLE
cyfs references in human services namespace

### ISSUE THREAD

**Issue by webb** [NIEM/NIEM-Releases#4]
In commit 0324336b6643265ce68802c967da0308873234cf

Definition of element hs:BiologicalParentDeterminationMethodText contains reference to cyfs.

> A narrative alternative to cyfs:BiologicalParentDeterminationMethodCode to describe the method by which a  biological relationship between a parent and child is legally determined.

Definition of element hs:SchoolResourceOfficerEducationOrganizationAssociationAugmentationPoint contains reference to cyfs.

> An augmentation point for type cyfs:SchoolResourceOfficerEducationOrganizationAssociationType

**Comment by ctraver** [comment]
Webb, this looks like an easy fix.  I'll ask the HSD team to suggest new definitions to replace.

**Comment by cdmgtri** [comment]
Corrected in NIEM 4.1.
