### ISSUE TITLE
changelog suggestion: use git! 

### ISSUE THREAD

**Issue by rebeccawilliams** [NIEM/NIEM-Releases#5]
I like that the detailed changelog is included in this repo. Would it also be possible to upload each release as a CSV on GitHub to view the changes via GitHub's version control? (see [this example](https://github.com/project-open-data/project-open-data.github.io/commit/17c453ed973eae44f78b6888ead2969365d6b7d6#diff-eb5432b8a6c7ad485135943e637997f0))

**Comment by webb** [comment]
NIEM 4.0 CSVs are on branch maintain-niem-4.0 as /csv/niem-4.0.

We haven't posted older (e.g., NIEM 3.2) CSVs. Do you have a need for them?

One piece of the NIEM architecture is that old things never go away & that multiple releases can work together; to support that some files are placed in unique locations for each release, which hinders github's basic diff view for those files. You can get close to it with `git diff --word-diff=color`, like:

```bash
$ git diff --word-diff=color niem-3.2:niem/niem-core/3.0/niem-core.xsd niem-4.0:niem/niem-core/4.0/niem-core.xsd
```
