### ISSUE TITLE
Create substitution groups for street direction codes

### ISSUE THREAD

**Issue by cdmgtri** [NIEM/NIEM-Releases#65]
Core has elements for street pre- and post-direction text fields.  The Justice domains has a code set for street directions.  Create substitution groups in Core to make the text and code elements available together.
 
### Current:

- nc:StreetType
  - nc:StreetFullText
  - nc:StreetNumberText
  - **nc:StreetPredirectionalText**
  - nc:StreetName
  - nc:StreetCategoryText
  - **nc:StreetPostdirectionalText**
  - nc:StreetExtensionText
  - nc:StreetAugmentationPoint
- j:StreetAugmentationType
  - **j:StreetPostdirectionalCode**
  - **j:StreetPredirectionalCode**

### Proposed:

- nc:StreetType
  - nc:StreetFullText
  - nc:StreetNumberText
  - **nc:StreetPredirectionalAbstract**
    - **nc:StreetPredirectionalText**
    - **j:StreetPredirectionalCode**
  - nc:StreetName
  - nc:StreetCategoryText
  - **nc:StreetPostdirectionalAbstract**
    - **nc:StreetPostdirectionalText**
    - **j:StreetPostdirectionalCode**
  - nc:StreetExtensionText
  - nc:StreetAugmentationPoint

**Comment by DonClysdale** [comment]
Canada Post and USPS have defined lists of street types - would be good to incorporate those codes into NIEM/codes/canada_post/5.0/post-canada.xsd and update codes/usps_states to be more generically USPS and add in other mail related codes.

**Comment by cdmgtri** [comment]
The NBAC Harmonization Workgroup recommends creating the new substitution groups for street predirectional and postdirectional.  

See issue #80 for potential harmonization between the USPS and FBI NDEx directional code sets, and for a new code set representing Canada Post directional codes.

**Comment by cdmgtri** [comment]
Approved by the NBAC at the annual meeting.
