### ISSUE TITLE
Interpretation of percent values is underspecified

### ISSUE THREAD

**Issue by webb** [NIEM/NIEM-Releases#7]
In NIEM 4.0 (1a0ec9ee2fe7134af32dd18b5464c235eacef6be), elements `nc:ProbabilityPercent` and `nc:Percent`, and attribute `nc:confidencePercent` each have a type based in xs:decimal. However, documentation of these elements aren't clear in how to interpret their values. `nc:Percent` is clear (100% = value 100), but the others are vague. Suggest adding a PercentType that has a clear interpretation as "0" means 0%, "100" means 100%, etc.

Note that there are many values across NIEM that are percents, and there's no clear way to interpret them all.

**Comment by cdmgtri** [comment]
The definition of **nc:Percent** is currently: "A ratio, proper fraction, or percentage, with 100% represented as the value 100."

Proposal is to create a corresponding type **nc:PercentType** with a similar definition.  It would be based on type niem-xs:decimal (any decimal value).  This type would then be used for all percent-properties in NIEM to make clear the expected value set.

Percent properties currently in NIEM with type niem-xs:decimal:

- ag:ProducerSharePercent
- em:EventRegionalClosedHospitalsPercent
- em:StatusPercent
- hs:ChildSupportUnreimbursedExpensePercent
- it:RateOfExchangePercent
- it:ValuationAdjustmentPercent
- j:ItemTitleSalesTaxPercent
- j:VehicleBrandSalvagePercent
- mo:DamagePercent
- nc:ConfidencePercent
- nc:ConveyanceSalesTaxPercent
- nc:Percent
- nc:ProbabilityPercent
- scr:PersonConfidenceLevelPercent
- st:RoadwayGradeSlopePercent
- **nc:confidencePercent** (xs:decimal) - attribute under nc:NumericType

**Comment by cdmgtri** [comment]
The Harmonization Workgroup recommends creating type nc:PercentType to clearly define expected values.

Attribute nc:confidencePercent was also reviewed and is recommended to be removed (currently appears under nc:NumericType) so that all confidence percents are represented the same way, via element nc:ConfidencePercent in type nc:MetadataType.
