### ISSUE TITLE
nc:LocationAddress should be allowed to substitute nc:LocationAddressAbstract

### ISSUE THREAD

**Issue by DonClysdale** [NIEM/NIEM-Releases#72]
nc:LocationAddress should be allowed as valid location address for any nc:Location - i.e. should be substitutable for nc:LocationAddressAbstract

  <xs:element name="LocationAddress" type="nc:AddressType"  **substitutionGroup="nc:LocationAddressAbstract"** nillable="true">
    <xs:annotation>
      <xs:documentation>A set of location information, often described by postal information.</xs:documentation>
    </xs:annotation>
  </xs:element>

**Comment by cdmgtri** [comment]
Thanks for the feedback!

Since element nc:Address has the same type (nc:AddressType) and is already substitutable for nc:LocationAddressAbstract, do you think it would be better to just remove element nc:LocationAddress instead?  It seems like these two elements overlap enough to where they could be considered duplicates.  Are there any situations where you would use nc:LocationAddress but couldn't use nc:Address?

**Comment by DonClysdale** [comment]
If you look at the definitions, nc:Address is a postal address and nc:LocationAddress is the address of a location. In the project we are working on, we want both addresses (location and postal) to be identified with the same location (and would have the same geographic coordinates etc).

So we want to use both nc:Address and nc:LocationAddress at the same time - on an nc:Location.

**Comment by cdmgtri** [comment]
Related address elements currently in NIEM:

**nc:Address** (nc:AddressType) -  A postal location to which paper mail can be directed.

- nc:LocationType
  - nc:LocationAddressAbstract
    - nc:Address (nc:AddressType)

---

**nc:LocationAddress** (nc:AddressType) - A set of location information, often described by postal information.

Currently does not appear under a type or in a substitution group.

---

**nc:ContactMailingAddress** (nc:AddressType) - A postal address by which a person or organization may be contacted.

- nc:ContactInformationType
  - nc:ContactMeansAbstract
    - nc:ContactMailingAddress

**Comment by cdmgtri** [comment]
### Current nc:LocationType

- nc:LocationAddressAbstract
  - nc:Address (nc:AddressType) - A postal location to which paper mail can be directed.
  - nc:AddressCrossStreet (nc:CrossStreetType)
  - nc:AddressGrid (nc:AddressGridType)
  - nc:AddressHighway (nc:HighwayType)

### Proposed nc:LocationType

- nc:LocationAddressAbstract
  - nc:Address (nc:AddressType) - A set of location information, often described by postal information.
    - nc:MailingAddress (nc:AddressType) - A mailing address for a location.  This may or may not be the same as the location's physical address.
    - nc:PhysicalAddress (nc:AddressType) - A physical address for a location.  This may or may not be the same as the location's mailing address.
  - nc:AddressCrossStreet (nc:CrossStreetType)
  - nc:AddressGrid (nc:AddressGridType)
  - nc:AddressHighway (nc:HighwayType)

**Comment by cdmgtri** [comment]
The Harmonization Workgroup recommends making this change.
