### ISSUE TITLE
Make nc:PersonContactInformation the substitution head for all the nc:PersonXXXContactInformation elements

### ISSUE THREAD

**Issue by DonClysdale** [NIEM/NIEM-Releases#75]
I would like to see this newly added nc:PersonContactInformation be the substitution head for all the nc:PersonXXXContactInformation elements which will reduce the nc:PersonType "sprawl". It would be cleaner to have only one nc:ContactInformationType element, nc:PersonContactInformation assign all the other nc:PersonXXXContactInformation elements to that substitutionGroup and remove them from nc:PersonType.

Current Elements to remove from nc:PersonType (after assigning them to substitutionGroup="nc:PersonContactInformation"):
 
nc:PersonHomeContactInformation (nc:ContactInformationType)
                 A means of contacting a person at home.

nc:PersonEmergencyContactInformation (nc:ContactInformationType)
                 A means of contacting someone in the event of an emergency.

nc:EmploymentContactInformation (nc:ContactInformationType)
                A means of contacting a person at work.

**Comment by cdmgtri** [comment]
The Harmonization Workgroup discussed this proposal.  

The major pro is that it helps to reduce some sprawl in nc:PersonType.  The major con is that this change would no longer allow you to assigned individual cardinality constraints to the substitutions - cardinality could only be assigned to the substitution group head.

The workgroup is willing to recommend the change, but would like a broader conversation with the NBAC and the NTAC regarding ideas about how to reduce sprawl across the model (#88), to see if there is a way to apply business rules (like cardinality constraints) to substitutions (#89), and to consider a new SSGT / tool feature that would allow you to inline substitutions in a subset directly and apply cardinality (#87).

**Comment by cdmgtri** [comment]
Approved by the NBAC at the annual meeting.

**Comment by cdmgtri** [comment]
After additional discussion with the Harmonization Work Group, it was decided to leave the contact information elements directly under nc:PersonType rather than bundling them into a substitution group since this allows users to set specific cardinality requirements in IEPDs and since NIEM is not using substitution groups as a means to reduce large object sizes.
