### ISSUE TITLE
Consider adding metadata for empty values

### ISSUE THREAD

**Issue by cdmgtri** [NIEM/NIEM-Releases#76]
Consider adding new metadata so that an explanation can be provided for empty values in a message.  Reasons might include that the information is unknown, the information is in progress or pending, the information is not allowed to be shared, etc.

There are two code sets currently in the model that define yes / no / unknown codes that may be able to be replaced with a boolean and the use of this metadata:

- em:TernaryIndicatorCodeSimpleType
- hs:JuvenileFamilyFinancialProblemCodeSimpleType

There are also IEPDs that re-create NIEM code sets in order to be able to add values to represent missing information.

This new metadata would provide a standard way across NIEM to document this sort of information.  It would also work for any kind of element (e.g., text, dates, numbers, booleans, elements with complex structures), not just codes.

**Comment by DonClysdale** [comment]
These are the values we think we need:

- Not Applicable: used when there is no valid value for a given reference domain that is linked to a column in a data set. As an example, a data set is capturing the province/state of a benefit recipient; however, the benefit recipient does not live in the country and therefore does not have a valid province/state. Rather than leaving the answer empty, the value of Not Applicable is used to indicate the absence of a valid answer in the given context.

- Not Known: used when no value is provided or the value provided is not valid as defined by the reference domain linked to the column in a data set. In the simplest terms, Not Known means we don't have a valid value and we don't know why we don't have a valid value. There are a number of legitimate scenarios under which Not Known is used: a user refuses to provide a valid value,  a user forgets to provide a valid value, a user provides an incorrect value and refuses to fix it.

**Comment by cdmgtri** [comment]
The Harmonization Workgroup recommends the addition of this metadata.  

Basic requirements are a substitution group and a code set with common reasons why no information was provided, plus a text field where more information can be provided.  One possibility is to add it to the existing nc:MetadataType.

Since the NTAC is currently reviewing privacy metadata and metadata in general, suggest this be reviewed as well in case the NTAC has special recommendations for how this should be implemented.

**Comment by webb** [comment]
This seems like a good, straightforward use of Metadata.
They may want to consider more values, like `nilReason` in GML, which has *inapplicable*, *unknown*, *missing*, *withheld*.
NBAC could define attributes that could be applied in extension schema in an IEPD, but that may not be convenient to use.

**Comment by cdmgtri** [comment]
### Reference: GML NilReasonType

gml:NilReasonType defines a content model that allows recording of an explanation for a void value or other exception.


gml:NilReasonType is a union of the following enumerated values:

- **inapplicable**: there is no value
- **missing**: the correct value is not readily available to the sender of this data. Furthermore, a correct value may not exist
- **template**: the value will be available later
- **unknown**: the correct value is not known to, and not computable by, the sender of this data. However, a correct value probably exists
- **withheld**: the value is not divulged
- **"other:"+text:** other brief explanation, where text is a string of two or more characters with no included spaces
- anyURI which should refer to a resource which describes the reason for the exception

A particular community may choose to assign more detailed semantics to the standard values provided.  Alternatively, the URI method enables a specific or more complete explanation for the absence of a value to be provided elsewhere and indicated by-reference in an instance document.

```xml
<simpleType name="NilReasonEnumeration">
   <union>
     <simpleType>
       <restriction base="string">
         <enumeration value="inapplicable"/>
         <enumeration value="missing"/>
         <enumeration value="template"/>
         <enumeration value="unknown"/>
         <enumeration value="withheld"/>
      </restriction>
    </simpleType>
    <simpleType>
      <restriction base="string">
        <pattern value="other:\w{2,}"/>
      </restriction>
    </simpleType>
  </union>
</simpleType>

<simpleType name="NilReasonType">
 <union memberTypes="gml:NilReasonEnumeration anyURI"/>
</simpleType>
```

**Comment by cdmgtri** [comment]
The Harmonization Workgroup recommends adding a new substitution group to nc:MetadataType with text and code substitutions, using the enumerations and definitions for the new code set from the GML NilReasonEnumeration.  Will also add a description field for more detailed information about why a value was not provided or how it might be otherwise obtained.

**Comment by cdmgtri** [comment]
Added to the 5.0 beta.
