### ISSUE TITLE
Add street category and other mail-related codes

### ISSUE THREAD

**Issue by cdmgtri** [NIEM/NIEM-Releases#80]
Canada Post and USPS have defined lists of street types - would be good to incorporate those codes into NIEM/codes/canada_post/5.0/post-canada.xsd and update codes/usps_states to be more generically USPS and add in other mail related codes. That is create abstract type for nc:StreetCategoryText (say nc:StreetCategoryAbstract) with substitutions of nc:StreetCategoryText and can:StreetCategoryCode and/or usps:StreetCategoryCode

_Originally posted by @DonClysdale in https://github.com/NIEM/NIEM-Releases/issues/65#issuecomment-526595294_

**Comment by cdmgtri** [comment]
[USPS Publication 28](https://pe.usps.com/text/pub28/welcome.htm) defines several code tables that could be added to NIEM if there are use cases for them.  These could include:

- Street category codes:  [Appendix C1](https://pe.usps.com/text/pub28/28apc_002.htm)
  - Create a new abstract element **nc:StreetCategoryAbstract**
  - Add current element **nc:StreetCategoryText** as a substitution
  - Add new element **nc:StreetCategoryCode** (usps:StreetSuffixCodeType) as a substitution

- Secondary unit codes: [Appendix C2](https://pe.usps.com/text/pub28/28apc_003.htm)
  - NIEM currently has one text element to represent both the secondary unit category and the value together.  Would need to also create a new element for the value if we want to be able to represent the category as a code.  Something like...
  - nc:AddressSecondaryUnit
    - nc:AddressSecondaryUnitCategoryAbstract
      - nc:AddressSecondaryUnitCategoryText
      - nc:AddressSecondaryUnitCategoryCode (usps:SecondaryUnitCodeType)
    - nc:AddressSecondaryUnitFullText
    
- Directional codes: [Appendix I4](https://pe.usps.com/text/pub28/28api_007.htm)
  - Add **nc:StreetPredirectionalCode** (usps:DirectionalCodeType) as a substitute for element  nc:StreetPredirectionalAbstract
  - Add **nc:StreetPostdirectionalCode** (usps:DirectionalCodeType) as a substitute for element nc:StreetPredirectionalAbstract
  - Also review the similar Justice street directional codes (#65) using the NDEx code set to see if the Core / USPS code set would fulfill their requirements

**Comment by DonClysdale** [comment]
Link to Canada Post site https://www.canadapost.ca/web/en/kb/details.page?article=addressing_mail_accu&cattype=kb&cat=addressing&subcat=accuracy

**Comment by cdmgtri** [comment]
The Harmonization Workgroup recommends the proposed changes for street category and street directionals.  The USPS code set meets the FBI NDEx requirement for street directionals.  New substitutions and code sets for secondary units are not recommended at this time unless someone comes forward with a need to use them.

**Comment by cdmgtri** [comment]
Approved by the NBAC at the annual meeting.
