### ISSUE TITLE
Review the use of hyphens in folder paths and file names

### ISSUE THREAD

**Issue by cdmgtri** [NIEM/NIEM-Releases#81]
A comment was made that a lot of systems, including SAP, do not support hyphens in file names.   ISO 9660 doesn't support hyphens in file names either.  

Consider whether NIEM should replace hyphens in schema folder paths and file names with underscores.

**Comment by mikehulme** [comment]
The NTAC believes NIEM should continue to support hyphens in folder and file names, and does not see a need to replace hyphens with underscores. Both hyphens and underscores are widely used in folder and file names and are almost universally accepted by supported information systems applications and tools. For example, the _National Archives Records Express_ article **[Best Practices for File Naming](https://records-express.blogs.archives.gov/2017/08/22/best-practices-for-file-naming/)** encourages the use of both hyphens and underscores in file names. Supported versions of Windows and Unix-derivative operating systems and their associated file systems all support hyphens in folder and file names.

We have not been able to find any evidence that SAP software does not support hyphens in file names. If there is a case where SAP or other software does not support the use of hyphens in file names, one should consider if that is a defect in the software, given the preponderance of support for hyphens in file names.

While the original ISO 9660 standard excludes hyphens from the list of permitted characters in file names, Amendment 1 to the specification (published in 2013) harmonized ISO 9660 with the more widely used Joliet specification, permitting the use of hyphens in file names.

Finally, NIEM conformance does not require the use of specific file names, so in the rare case where an implementation cannot accommodate hyphens in folders and file names, the developers of that implementation are free to rename files and their associated references as needed (for example, to replace hyphens with underscores).

Therefore, the NTAC does not see a need to change the naming conventions (replacing hyphens with underscores) used in NIEM releases.

**Comment by cdmgtri** [comment]
The Harmonization Workgroup reviewed the NTAC's guidance and did not raise any further concerns about the topic.
