### ISSUE TITLE
Add new substitution groups to Core for easier inclusion of local code sets

### ISSUE THREAD

**Issue by cdmgtri** [NIEM/NIEM-Releases#82]
@DonClysdale will provide a list of potential substitution groups to add to Core.  This would make it easier to add local code sets to IEPDs, instead of having to create new augmentations to do so.

After reviewing this list, the Harmonization Workgroup and the NBAC should consider whether to review the rest of Core text elements for other potential substitution groups.  

_Note: Core contains 361 elements that use or are based on nc:TextType._

**Comment by DonClysdale** [comment]
add nc:ContactInformationCategoryAbstract on nc:ContactInformationType
replace nc:ActivityCategoryText with nc:ActivityCategoryAbstract on nc:ActivityType and update nc:ActivityCategoryText to substitute for nc:ActivityCategoryAbstract
replace nc:ActivityReasonText with nc:ActivityReasonAbstract on nc:ActivityType and update nc:ActivityReasonText to substitute for nc:ActivityReasonAbstract
replace nc:DispositionText with nc:DispositionAbstract on nc:CaseDispositionType and update nc:DispositionText to substitute for nc:DispositionAbstract
replace nc:DispositionReasonText with nc:DispositionReasonAbstract on nc:CaseDispositionType and update nc:DispositionReasonText to substitute for nc:DispositionReasonAbstract
replace nc:CaseDispositionDecisionCategoryText with nc:CaseDispositionDecisionCategoryAbstract on nc:CaseDispositionDecisionType and update nc:CaseDispositionDecisionCategoryText to substitute for nc:CaseDispositionDecisionCategoryAbstract
replace nc:ConditionViolationText with nc:ConditionViolationAbstract on nc:ConditionType and update nc:ConditionViolationText to substitute for nc:ConditionViolationAbstract

add nc:AssociationCategoryAbstract on nc:AssociationType and add nc:AssociationCategoryText as substitute for nc:AssociationCategoryAbstract
add nc:EmploymentCategoryAbstract on nc:PersonEmploymentAssociationType and add nc:EmploymentCategoryText as substitute for nc:EmploymentCategoryAbstract
add nc:OrganizationSizeAbstract on nc:OrganizationType and add nc:OrganizationSizeText as substitute for nc:OrganizationSizeAbstract
add nc:ObligationEntityCategoryAbstract on nc:OrganizationType and add nc:OrganizationSizeText as substitute for nc:OrganizationSizeAbstract

replace nc:BinaryFormatText with nc:BinaryFormatAbstract on nc:BinaryType and update nc:BinaryFormatText to substitute for nc:BinaryFormatAbstract

replace nc:CapabilityGeneralCategoryText with nc:CapabilityCategoryAbstract on nc:CapabilityType and update nc:CapabilityGeneralCategoryText to substitute for nc:CapabilityCategoryAbstract
replace nc:CapabilityCategoryText with nc:CapabilityCategoryAbstract on nc:CapabilityType and update nc:CapabilityCategoryText to substitute for nc:CapabilityCategoryAbstract

replace nc:CaseGeneralCategoryText with nc:CaseCategoryAbstract on nc:CaseType and update nc:CaseGeneralCategoryText to substitute for nc:CaseCategoryAbstract
replace nc:CaseCategoryText with nc:CaseCategoryAbstract on nc:CaseType and update nc:CaseCategoryText to substitute for nc:CaseCategoryAbstract
replace nc:CaseSubCategoryText with nc:CaseCategoryAbstract on nc:CaseType and update nc:CaseSubCategoryText to substitute for nc:CaseCategoryAbstract

replace nc:ContactRadioCategoryText with nc:ContactRadioCategoryAbstract on nc:ContactRadioType and update nc:ContactRadioCategoryText to substitute for nc:ContactRadioCategoryAbstract
replace nc:DocumentRelationText with nc:DocumentRelationAbstract on nc:DocumentAssociationType and update nc:DocumentRelationText to substitute for nc:DocumentRelationAbstract
replace nc:DocumentDisputedReasonText with nc:DocumentDisputedReasonAbstract on nc:DocumentType and update nc:DocumentDisputedReasonText to substitute for nc:DocumentDisputedReasonAbstract
replace nc:DocumentFormatText with nc:DocumentFormatAbstract on nc:DocumentType and update nc:DocumentFormatText to substitute for nc:DocumentFormatAbstract
replace nc:DocumentManagementCyclePeriodText with nc:DocumentManagementCyclePeriodAbstract on nc:DocumentType and update nc:DocumentManagementCyclePeriodText to substitute for nc:DocumentManagementCyclePeriodAbstract
replace nc:DocumentMediaCategoryText with nc:DocumentMediaCategoryAbstract on nc:DocumentType and update nc:DocumentMediaCategoryText to substitute for nc:DocumentMediaCategoryAbstract
replace nc:DocumentMediumText with nc:DocumentMediumAbstract on nc:DocumentType and update nc:DocumentMediumText to substitute for nc:DocumentMediumAbstract
replace nc:DocumentRightsText with nc:DocumentRightsAbstract on nc:DocumentType and update nc:DocumentRightsText to substitute for nc:DocumentRightsAbstract
replace nc:DocumentFormatCategoryText with nc:DocumentFormatCategoryAbstract on nc:DocumentType and update nc:DocumentFormatCategoryText to substitute for nc:DocumentFormatCategoryAbstract
replace nc:DrugStrengthText with nc:DrugStrengthAbstract on nc:DrugType and update nc:DrugStrengthText to substitute for nc:DrugStrengthAbstract
replace nc:DrugCoverageExceptionReasonText with nc:DrugCoverageExceptionReasonAbstract on nc:DrugType and update nc:DrugCoverageExceptionReasonText to substitute for nc:DrugCoverageExceptionReasonAbstract
replace nc:FacilityMemberCategoryText with nc:FacilityMemberCategoryAbstract on nc:FacilityType and update nc:FacilityMemberCategoryText to substitute for nc:FacilityMemberCategoryAbstract
replace nc:FacilitySecurityLevelText with nc:FacilitySecurityLevelAbstract on nc:FacilityType and update nc:FacilitySecurityLevelText to substitute for nc:FacilitySecurityLevelAbstract
replace nc:FinancialAccountCategoryText with nc:FinancialAccountCategoryAbstract on nc:FinancialAccountType and update nc:FinancialAccountCategoryText to substitute for nc:FinancialAccountCategoryAbstract
replace nc:IdentificationSourceText with nc:IdentificationSourceAbstract on nc:IdentificationType and update nc:IdentificationSourceText to substitute for nc:IdentificationSourceAbstract
replace nc:IncidentDayPeriodText with nc:IncidentDayPeriodAbstract on nc:IncidentType and update nc:IncidentDayPeriodText to substitute for nc:IncidentDayPeriodAbstract
replace nc:ItemActionText with nc:ItemActionAbstract on nc:ItemType and update nc:ItemActionText to substitute for nc:ItemActionAbstract
replace nc:ItemConditionText with nc:ItemConditionAbstract on nc:ItemType and update nc:ItemConditionText to substitute for nc:ItemConditionAbstract
replace nc:ItemUsageText with nc:ItemUsageAbstract on nc:ItemType and update nc:ItemUsageText to substitute for nc:ItemUsageAbstract
replace nc:ItemOwnershipCategoryText with nc:ItemOwnershipCategoryAbstract on nc:ItemType and update nc:ItemOwnershipCategoryText to substitute for nc:ItemOwnershipCategoryAbstract

add nc:LocaleCensusGeographyAbstract
replace nc:LocaleCensusBlockID and nc:LocaleCensusTractID with nc:LocaleCensusGeographyAbstract in nc:LocaleType and update nc:LocaleCensusBlockID and nc:LocaleCensusTractID to substitute for nc:LocaleCensusBlockID and nc:LocaleCensusGeographyAbstract
add nc:LocaleRegionAbstract
replace nc:LocaleCommunityName and nc:LocaleDistrictName and nc:LocaleNeighborhoodName and nc:LocaleRegionName and nc:LocaleSubdivisionName and nc:LocaleZoneName in LocaleType with nc:LocaleRegionAbstract in nc:LocaleType and update nc:LocaleCommunityName and nc:LocaleDistrictName and nc:LocaleNeighborhoodName and nc:LocaleRegionName and nc:LocaleSubdivisionName and nc:LocaleZoneName to substitute for nc:LocaleRegionAbstract
add nc:LocaleEmergencyServicesAbstract
replace nc:LocaleEmergencyServicesName and nc:LocaleFireJurisdictionID and nc:LocalePoliceBeatText and nc:LocalePoliceGridText and nc:LocalePoliceJurisdictionID and nc:LocaleEmergencyServicesJurisdictionID in LocaleType with nc:LocaleEmergencyServicesAbstract in nc:LocaleType and update nc:LocaleEmergencyServicesName and nc:LocaleFireJurisdictionID and nc:LocalePoliceBeatText and nc:LocalePoliceGridText and nc:LocalePoliceJurisdictionID and nc:LocaleEmergencyServicesJurisdictionID to substitute for nc:LocaleEmergencyServicesAbstract
remove ref to nc:LocaleJudicialDistrictName in LocaleType and update nc:LocaleJudicialDistrictName to substitute for nc:LocaleJudicialDistrictAbstract

add nc:LocationLandmarkAbstract
replace nc:LocationLandMarkText with nc:LocationLandmarkAbstract in nc:LocationType and update nc:LocationLandmarkText to substitute for nc:LocationLandmarkAbstract
add nc:LocationLandmarkName type nc:ProperNameTextType and substitute for nc:LocationLandmarkAbstract

replace nc:MeasureMethodText with nc:MeasureMethodAbstract on nc:MeasureType and update nc:MeasureMethodText to substiture for nc:MeasureMethodAbstract
replace nc:MedicalConditionText with nc:MedicalConditionAbstract on nc:MedicalConditionType and update nc:MedicalConditionText to substiture for nc:MedicalConditionAbstract
replace nc:MedicalConditionCauseText with nc:MedicalConditionCauseAbstract on nc:MedicalConditionType and update nc:MedicalConditionCauseText to substiture for nc:MedicalConditionCauseAbstract
replace nc:MedicalConditionSeverityText with nc:MedicalConditionSeverityAbstract on nc:MedicalConditionType and update nc:MedicalConditionSeverityText to substiture for nc:MedicalConditionSeverityAbstract
replace nc:MessageSubjectText with nc:MessageSubjectAbstract on nc:MessageType and update nc:MessageSubjectText to substitute for nc:MessageSubjectAbstract
replace nc:MessageFATCAUsageRestrictionText with nc:MessageUsageRestrictionAbstract on nc:MessageType and update nc:MessageFATCAUsageRestrictionText to substitute for nc:MessageUsageRestrictionAbstract

replace nc:ReportingOrganizationText with nc:ReportingOrganizationAbstract on nc:MetadataType and update nc:ReportingOrganizationText to substitute for nc:ReportingOrganizationAbstract
replace nc:ReportingPersonRoleText with nc:ReportingPersonRoleAbstract on nc:MetadataType and update nc:ReportingPersonRoleText to substitute for nc:ReportingPersonRoleAbstract
replace nc:ReportingPersonText with nc:ReportingPersonAbstract on nc:MetadataType and update nc:ReportingPersonText to substitute for nc:ReportingPersonAbstract
replace nc:SensitivityText with nc:SensitivityAbstract on nc:MetadataType and update nc:SensitivityText to substitute for nc:SensitivityAbstract
replace nc:SourceIDText and nc:SourceText with nc:SourceAbstract on nc:MetadataType and update nc:SourceIDText and nc:SourceText to substitute for nc:SourceAbstract
replace nc:SourceContactPersonText with nc:SourceContactPersonAbstract on nc:MetadataType and update nc:SourceContactPersonText to substitute for nc:SourceContactPersonAbstract
replace nc:MilitaryReleaseCategoryText with nc:MilitaryReleaseCategoryAbstract on nc:MilitarySummaryType and update nc:MilitaryReleaseCategoryText to substitute for nc:MilitaryReleaseCategoryAbstract
replace nc:ObligationPeriodText with nc:ObligationPeriodAbstract on nc:ObligationRecurrenceType and update nc:ObligationPeriodText to substitute for nc:ObligationPeriodAbstract
replace nc:ObligationCategoryText with nc:ObligationCategoryAbstract on nc:ObligationType and update nc:ObligationCategoryText to substitute for nc:ObligationCategoryAbstract

remove ref to nc:OrganizationLEIIdentification and nc:OrganizationLocalIdentification and nc:OrganizationOtherIdentification and nc:OrganizationTaxIdentification on nc:OrganizationType and update nc:OrganizationLEIIdentification and nc:OrganizationLocalIdentification and nc:OrganizationOtherIdentification and nc:OrganizationTaxIdentification to substitute for nc:OrganizationIdentification

replace nc:OrganizationActivityText with nc:OrganizationActivityAbstract on nc:OrganizationType and update nc:OrganizationActivityText to substitute for nc:OrganizationActivityAbstract
replace nc:PermitUsageText with nc:PermitUsageAbstract on nc:PermitType and update nc:PermitUsageText to substitute for nc:PermitUsageAbstract
replace nc:PersonDisunionReasonText with nc:PersonDisunionReasonAbstract on nc:PersonDisunionType and update nc:PersonDisunionReasonText to substitute for nc:PersonDisunionReasonAbstract
replace nc:EmployeePositionName with nc:EmployeePositionAbstract on nc:PersonEmploymentAssociationType and update nc:EmployeePositionName to substitute for nc:EmployeePositionAbstract
replace nc:EmployeeRankText with nc:EmployeeRankAbstract on nc:PersonEmploymentAssociationType and update nc:EmployeeRankText to substitute for nc:EmployeeRankAbstract
replace nc:EmployeeShiftText with nc:EmployeeShiftAbstract on nc:PersonEmploymentAssociationType and update nc:EmployeeShiftText to substitute for nc:EmployeeShiftAbstract
replace nc:EmployeeEarningsRateText with nc:EmployeeEarningsRateAbstract on nc:PersonEmploymentAssociationType and update nc:EmployeeEarningsRateText to substitute for nc:EmployeeEarningsRateAbstract
replace nc:PersonNamePrefixText with nc:PersonNamePrefixAbstract on nc:PersonNameType and update nc:PersonNamePrefixText to substitute for nc:PersonNamePrefixAbstract
replace nc:PersonNameSuffixText with nc:PersonNameSuffixAbstract on nc:PersonNameType and update nc:PersonNameSuffixText to substitute for nc:PersonNameSuffixAbstract
replace nc:PersonNameSalutationText with nc:PersonNameSalutationAbstract on nc:PersonNameType and update nc:PersonNameSalutationText to substitute for nc:PersonNameSalutationAbstract
replace nc:PersonSurNamePrefixText with nc:PersonSurNamePrefixAbstract on nc:PersonNameType and update nc:PersonSurNamePrefixText to substitute for nc:PersonSurNamePrefixAbstract
replace nc:ResidenceOccupancyCategoryText with nc:ResidenceOccupancyCategoryAbstract on nc:PersonResidenceAssociationType and update nc:ResidenceOccupancyCategoryText to substitute for nc:ResidenceOccupancyCategoryAbstract
replace nc:ResidencePaymentPeriodText with nc:ResidencePaymentPeriodAbstract on nc:PersonResidenceAssociationType and update nc:ResidencePaymentPeriodText to substitute for nc:ResidencePaymentPeriodAbstract
replace nc:PersonAccentText with nc:PersonAccentAbstract on nc:PersonType and update nc:PersonAccentText to substitute for nc:PersonAccentAbstract
replace nc:PersonComplexionText with nc:PersonComplexionAbstract on nc:PersonType and update nc:PersonComplexionText to substitute for nc:PersonComplexionAbstract
replace nc:PersonEducationLevelText with nc:PersonEducationLevelAbstract on nc:PersonType and update nc:PersonEducationLevelText to substitute for nc:PersonEducationLevelAbstract
replace nc:PersonHairCategoryText with nc:PersonHairCategoryAbstract on nc:PersonType and update nc:PersonHairCategoryText to substitute for nc:PersonHairCategoryAbstract
replace nc:PersonHandednessText with nc:PersonHandednessAbstract on nc:PersonType and update nc:PersonHandednessText to substitute for nc:PersonHandednessAbstract
replace nc:PersonMentalStateText with nc:PersonMentalStateAbstract on nc:PersonType and update nc:PersonMentalStateText to substitute for nc:PersonMentalStateAbstract
replace nc:PersonLearningDisabilityText and nc:PersonPhysicalDisabilityText with nc:PersonDisabilityAbstract on nc:PersonType and update nc:PersonLearningDisabilityText and nc:PersonPhysicalDisabilityText to substitute for nc:PersonDisabilityAbstract
replace nc:PersonSexualOrientationText with nc:PersonSexualOrientationAbstract on nc:PersonType and update nc:PersonSexualOrientationText to substitute for nc:PersonSexualOrientationAbstract
remove ref to nc:PhysicalFeatureGeneralCategoryText in nc:PhysicalFeatureType and update nc:PhysicalFeatureGeneralCategoryText to substitute for nc:PhysicalFeatureCategoryAbstract
replace nc:PhysicalFeatureLocationText with nc:PhysicalFeatureLocationAbstract on nc:PhysicalFeatureType and update nc:PhysicalFeatureLocationText to substitute for nc:PhysicalFeatureLocationAbstract
replace nc:ProgressComplianceText with nc:ProgressComplianceAbstract on nc:ProgressType and update nc:ProgressComplianceText to substitute for nc:ProgressComplianceAbstract
replace nc:ProgressTimeQuantityText with nc:ProgressTimeQuantityAbstract on nc:ProgressType and update nc:ProgressTimeQuantityText to substitute for nc:ProgressTimeQuantityAbstract
replace nc:PublicServiceChannelText with nc:PublicServiceChanneAbstract on nc:PublicServiceType and update nc:PublicServiceChannelText to substitute for nc:PublicServiceChannelAbstract
replace nc:RealEstateAcreageText with nc:RealEstateAcreageAbstract on nc:RealEstateType and update nc:RealEstateAcreageText to substitute for nc:RealEstateAcreageAbstract
replace nc:RecommendationSubjectText with nc:RecommendationSubjectAbstract on nc:RecommendationType and update nc:RecommendationSubjectText to substitute for nc:RecommendationSubjectAbstract
replace nc:ActivityRelationText with nc:ActivityRelationAbstract on nc:RelatedActivityAssociationType and update nc:ActivityRelationText to substitute for nc:ActivityRelationTextAbstract
replace nc:StreetPredirectionalText with nc:StreetPredirectionalAbstract on nc:StreetType and update nc:StreetPredirectionalText to substitute for nc:StreetPredirectionalAbstract
replace nc:StreetCategoryText with nc:StreetCategoryAbstract on nc:StreetType and update nc:StreetCategoryText to substitute for nc:StreetCategoryAbstract
replace nc:StreetPostdirectionalText with nc:StreetPostdirectionalAbstract on nc:StreetType and update nc:StreetPostdirectionalText to substitute for nc:StreetPostdirectionalAbstract
replace nc:StreetExtensionText with nc:StreetExtensionAbstract on nc:StreetType and update nc:StreetExtensionText to substitute for nc:StreetExtensionAbstract
replace nc:SubstanceFormText with nc:SubstanceFormAbstract on nc:SubstanceType and update nc:SubstanceFormText to substitute for nc:SubstanceFormAbstract
replace nc:VehicleColorInteriorText with nc:VehicleColorInteriorAbstract on nc:VehicleType and update nc:VehicleColorInteriorText to substitute for nc:VehicleColorInteriorAbstract
replace nc:WeaponUsageText with nc:WeaponUsageAbstract on nc:WeaponType and update nc:WeaponUsageText to substitute for nc:WeaponUsageAbstract

**Comment by cdmgtri** [comment]
## New properties

### nc:AssociationType

- nc:AssociationCategoryAbstract - *new*
  - nc:AssociationCategoryText - *new*

### nc:ContactInformationType

- nc:ContactInformationCategoryAbstract - *new*

### nc:ObligationType

- nc:ObligationEntityCategoryAbstract  - *new*
  - nc:ObligationEntityCategoryText  - *new*

### nc:OrganizationType

- nc:OrganizationSizeAbstract - *new*
  - nc:OrganizationSizeText - *new*

### nc:PersonEmploymentAssociationType

- nc:EmploymentCategoryAbstract - *new*
  - nc:EmploymentCategoryText - *new*

---

## Convert existing text elements to substitution groups

### nc:ActivityType

- **nc:ActivityCategoryText**
- nc:ActivityDescriptionText
- **nc:ActivityReasonText**

### nc:AddressGridType

- nc:AddressGridText

### nc:AddressType

- nc:AddressFullText
- nc:AddressPrivateMailboxText
- nc:AddressSecondaryUnitText

### nc:AnomalyType

- nc:AnomalyDescriptionText

### nc:AreaType

- nc:AreaDescriptionText

### nc:AssessmentType

- nc:AssessmentScoreText

### nc:AssociationType

- nc:AssociationDescriptionText

### nc:BinaryType

- nc:BinaryDescriptionText
- **nc:BinaryFormatText**
- nc:BinaryLocationText

### nc:CapabilityType

- **nc:CapabilityCategoryText**
- nc:CapabilityDescriptionText
- **nc:CapabilityGeneralCategoryText**

### nc:CaseDispositionDecisionType

- **nc:CaseDispositionDecisionCategoryText**
- nc:CaseDispositionDecisionText

### nc:CaseType

- **nc:CaseCategoryText**
- **nc:CaseGeneralCategoryText**
- nc:CaseResolutionText
- **nc:CaseSubCategoryText**
- nc:CaseTitleText

### nc:CaveatType

- nc:CaveatIssuingAuthorityText
- nc:CaveatText

### nc:CommentType

- nc:CommentAuthorText
- nc:CommentText
- nc:CommentTitleText

### nc:ConditionType

- **nc:ConditionViolationText**

### nc:ContactInformationType

- nc:ContactEntityDescriptionText
- nc:ContactInformationDescriptionText

### nc:ContactRadioType

- **nc:ContactRadioCategoryText**
- nc:ContactRadioChannelText

### nc:ConveyanceType

- nc:ConveyanceCargoText

### nc:CrisisType

- nc:CrisisDescriptionText

### nc:CrossStreetType

- nc:CrossStreetDescriptionText

### nc:DecalType

- **nc:DecalColorText** - *CDM*

### nc:DirectDialTelephoneNumberType

- nc:DirectDialTelephoneNetworkText

### nc:DispositionType

- nc:DispositionDescriptionText
- **nc:DispositionReasonText**
- nc:DispositionReportedAuthorityText
- **nc:DispositionText**

### nc:DocumentAssociationType

- **nc:DocumentRelationText**

### nc:DocumentType

- nc:DocumentCategoryDescriptionText
- nc:DocumentContentListText
- nc:DocumentDescriptionText
- nc:DocumentDispositionInstructionText
- **nc:DocumentDisputedReasonText**
- nc:DocumentFileExtensionText
- **nc:DocumentFormatCategoryText**
- **nc:DocumentFormatText**
- nc:DocumentKeywordText
- **nc:DocumentManagementCyclePeriodText**
- **nc:DocumentMediaCategoryText**
- **nc:DocumentMediumText**
- nc:DocumentRelatedResourceText
- **nc:DocumentRightsText**
- nc:DocumentSourceText
- nc:DocumentSummaryText
- nc:DocumentSupplementalMarkingText
- nc:DocumentTitleAlternativeText
- nc:DocumentTitleText

### nc:DrugType

- **nc:DrugCoverageExceptionReasonText**
- **nc:DrugStrengthText**

### nc:EducationQualificationType

- nc:EducationQualificationDescriptionText
- **nc:EducationQualificationInstitutionText**

### nc:EducationType

- nc:EducationDescriptionText

### nc:ElectronicAddressType

- nc:ElectronicAddressDescriptionText

### nc:FacilityType

- nc:FacilityCapacityDescriptionText
- nc:FacilityDescriptionText
- **nc:FacilityMemberCategoryText**
- **nc:FacilitySecurityLevelText**

### nc:FinancialAccountType

- **nc:FinancialAccountCategoryText**

### nc:GenericEntityType

- nc:EntityDescriptionText

### nc:HighwayType

- nc:HighwayFullText
- nc:HighwayPositionText

### nc:IdentificationType

- nc:IdentificationCategoryDescriptionText
- **nc:IdentificationSourceText**

### nc:IdentityType

- nc:IdentityCreationEventText
- nc:IdentityTerminationEventText

### nc:IncidentType

- **nc:IncidentDayPeriodText**
- nc:IncidentObservationText

### nc:InjuryType

- nc:InjuryDescriptionText

### nc:IntangibleItemType

- nc:IntellectualItemBusinessAreaText

### nc:IntellectualPropertyType

- nc:IntellectualPropertyCreationEventText
- nc:IntellectualPropertyTerminationEventText

### nc:ItemType

- **nc:ItemActionText**
- nc:ItemColorDescriptionText
- **nc:ItemConditionText**
- nc:ItemDescriptionText
- **nc:ItemOwnershipCategoryText**
- nc:ItemPossessionDescriptionText
- nc:ItemSizeDescriptionText
- **nc:ItemUsageText**

### nc:ItemValueType

- nc:ItemValueDescriptionText

### nc:JurisdictionType

- nc:JurisdictionDescriptionText
- nc:JurisdictionRestrictionText

### nc:LocaleType

- **nc:LocaleCensusBlockID** - *Substitute for new nc:LocaleCensusGeographyAbstract*
- **nc:LocaleCensusTractID** - *Substitute for new nc:LocaleCensusGeographyAbstract*
- nc:LocaleDescriptionText
- **nc:LocaleEmergencyServicesName** - *Substitute for new nc:LocaleEmergencyServicesAbstract*
- **nc:LocaleFireJurisdictionID** - *Substitute for new nc:LocaleEmergencyServicesAbstract*
- **nc:LocalePoliceBeatText** - *Substitute for new nc:LocaleEmergencyServicesAbstract*
- **nc:LocalePoliceGridText** - *Substitute for new nc:LocaleEmergencyServicesAbstract*
- **nc:LocalePoliceJurisdictionID** - *Substitute for new nc:LocaleEmergencyServicesAbstract*
- **nc:LocaleEmergencyServicesJurisdictionID** - *Substitute for new nc:LocaleEmergencyServicesAbstract*
- nc:LocaleJudicialDistrictAbstract
  - j:JudicialDistrictCode
- **nc:LocaleJudicialDistrictName** - *Move to existing nc:LocaleJudicialDistrictAbstract subst group*
- nc:LocaleDistrictIdentification
- **nc:LocaleCommunityName** - *Substitute for new nc:LocaleRegionAbstract*
- **nc:LocaleDistrictName** - *Substitute for new nc:LocaleRegionAbstract*
- **nc:LocaleNeighborhoodName** - *Substitute for new nc:LocaleRegionAbstract*
- **nc:LocaleRegionName** - *Substitute for new nc:LocaleRegionAbstract*
- **nc:LocaleSubdivisionName** - *Substitute for new nc:LocaleRegionAbstract*
- **nc:LocaleZoneName** - *Substitute for new nc:LocaleRegionAbstract*

#### Proposed nc:LocaleType

- **nc:LocaleCensusGeographyAbstract** - *new*
  - **nc:LocaleCensusBlockID**
  - **nc:LocaleCensusTractID**
- nc:LocaleDescriptionText
- **nc:LocaleEmergencyServicesAbstract** - *new*
  - **nc:LocaleEmergencyServicesName**
  - **nc:LocaleFireJurisdictionID**
  - **nc:LocalePoliceBeatText**
  - **nc:LocalePoliceGridText**
  - **nc:LocalePoliceJurisdictionID**
  - **nc:LocaleEmergencyServicesJurisdictionID**
- nc:LocaleJudicialDistrictAbstract
  - j:JudicialDistrictCode
  - **nc:LocaleJudicialDistrictName**
- nc:LocaleDistrictIdentification
- **nc:LocaleRegionAbstract** - *new*
  - **nc:LocaleCommunityName**
  - **nc:LocaleDistrictName**
  - **nc:LocaleNeighborhoodName**
  - **nc:LocaleRegionName**
  - **nc:LocaleSubdivisionName**
  - **nc:LocaleZoneName**

### nc:LocationPartType

- nc:LocationBedText
- nc:LocationBuildingText
- nc:LocationFloorText
- nc:LocationPartText
- nc:LocationRoomText
- nc:LocationSectionText
- nc:LocationSuiteText

### nc:LocationType

- nc:LocationDescriptionText
- nc:LocationDirectionsText
- **nc:LocationLandmarkText** - *Also add new nc:LocationLandmarkName*
- nc:LocationRangeDescriptionText
- nc:LocationSurroundingAreaDescriptionText

### nc:MapLocationType

- nc:MapCoordinateFullText
- nc:MapElevationCoordinateText
- nc:MapHorizontalCoordinateText
- nc:MapLocationDescriptionText
- nc:MapQuadrantText
- nc:MapVerticalCoordinateText

### nc:MeasureType

- nc:MeasureCommentText
- nc:MeasureDescriptionText
- **nc:MeasureMethodText**

### nc:MedicalConditionType

- **nc:MedicalConditionCauseText**
- nc:MedicalConditionDescriptionText
- **nc:MedicalConditionSeverityText**
- **nc:MedicalConditionText**

### nc:MessageType

- **nc:MessageFATCAUsageRestrictionText**
- **nc:MessageSubjectText**
- nc:MessageText

### nc:MetadataType

- nc:MetadataDescriptionText
- nc:MetadataDistributionText
- nc:MetadataEmptyReasonDescriptionText
- **nc:MetadataReportingOrganizationText**
- **nc:MetadataReportingPersonRoleText**
- **nc:MetadataReportingPersonText**
- **nc:MetadataSensitivityText**
- **nc:MetadataSourceContactPersonText**
- **nc:MetadataSourceIDText**
- nc:MetadataSourceText

### nc:MilitarySummaryType

- nc:MilitaryDischargeRankText
- nc:MilitaryDutiesText
- nc:MilitaryExemptionDescriptionText
- nc:MilitaryHighRankText
- **nc:MilitaryReleaseCategoryText**
- nc:MilitaryWorkSkillText

### nc:ObligationExemptionType

- nc:ObligationExemptionDescriptionText

### nc:ObligationRecurrenceType

- **nc:ObligationPeriodText**

### nc:ObligationType

- **nc:ObligationCategoryText**
- nc:ObligationProgressDescriptionText
- nc:ObligationRequirementDescriptionText

### nc:OrganizationType

- nc:OrganizationAbbreviationText
- **nc:OrganizationActivityText**
- nc:OrganizationDescriptionText

### nc:PermitType

- **nc:PermitUsageText**

### nc:PersonDisunionType

- **nc:PersonDisunionReasonText**

### nc:PersonEmploymentAssociationType

- **nc:EmployeeEarningsRateText**
- **nc:EmployeePositionName**
- **nc:EmployeeRankText**
- **nc:EmployeeShiftText**

### nc:PersonEncounterType

- nc:EncounterCommentText

### nc:PersonNameType

- nc:personNameCommentText
- **nc:PersonNamePrefixText**
- **nc:PersonNameSalutationText**
- **nc:PersonNameSuffixText**
- **nc:PersonSurNamePrefixText**

### nc:PersonResidenceAssociationType

- nc:ResidenceDescriptionText
- **nc:ResidenceOccupancyCategoryText**
- **nc:ResidencePaymentPeriodText**

### nc:PersonType

- **nc:PersonAccentText**
- nc:PersonAgeDescriptionText
- **nc:PersonComplexionText**
- nc:PersonDescriptionText
- nc:PersonDisguiseDescriptionText
- nc:PersonGeneralAppearanceDescriptionText
- nc:PersonHairAppearanceText
- **nc:PersonHairCategoryText**
- **nc:PersonHandednessText**
- nc:PersonHeightDescriptionText
- nc:PersonJewelryDescriptionText
- **nc:PersonLearningDisabilityText**
- nc:PersonMedicalDescriptionText
- nc:PersonMedicationRequiredText
- **nc:PersonMentalStateText**
- nc:PersonMoodDescriptionText
- nc:PersonPhysicalDisabilityText
- **nc:PersonSexualOrientationText**
- nc:PersonSpeechDescriptionText
- nc:PersonVisionPrescriptionText
- nc:PersonWeightDescriptionText

### nc:PhysicalFeatureType

- nc:PhysicalFeatureDescriptionText
- **nc:PhysicalFeatureGeneralCategoryText**
- **nc:PhysicalFeatureLocationText**

### nc:ProgramType

- nc:ProgramPurposeText

### nc:ProgressType

- **nc:ProgressComplianceText**
- **nc:ProgressTimeQuantityText**

### nc:PublicationType

- nc:PublicationAuthorText
- nc:PublicationPublisherText
- nc:PublicationSubjectText
- nc:PublicationTitleText

### nc:PublicServiceType

- **nc:PublicServiceChannelText**
- nc:PublicServiceDescriptionText

### nc:QuantityType

- nc:quantityUnitText

### nc:RealEstateType

- **nc:RealEstateAcreageText**
- nc:RealEstateBoundaryDescriptionText

### nc:RecommendationType

- nc:RecommendationDescriptionText
- **nc:RecommendationSubjectText**
- nc:RecommendationText

### nc:RelatedActivityAssociationType

- **nc:ActivityRelationText**

### nc:RelativeLocationType

- nc:RelativeLocationDescriptionText

### nc:RequestType

- nc:RequestDecisionText
- nc:RequestDescriptionText
- nc:RequestText

### nc:ScheduleDayType

- nc:ScheduleActivityText

### nc:ScheduleType

- nc:ScheduleDescriptionText
- nc:ScheduleExceptionsDescriptionText

### nc:SiteType

- nc:SiteMobileDescriptionText
- nc:SiteSpecialInformationText

### nc:SoftwareType

- nc:SoftwareDescriptionText

### nc:StatusType

- nc:StatusCommentText
- nc:StatusDescriptionText
- nc:StatusIssuerText

### nc:StreetType

- **nc:StreetExtensionText**
- nc:StreetFullText
- nc:StreetNumberText

### nc:SubstanceType

- nc:SubstanceCompositionDescriptionText
- nc:SubstanceContainerDescriptionText
- **nc:SubstanceFormText**
- nc:SubstanceFoundDescriptionText

### nc:TaskType

- nc:TaskCriteriaForSuccessText
- nc:TaskDescriptionText

### nc:TelephoneNumberType

- nc:TelephoneNumberDescriptionText

### nc:TreatmentType

- nc:TreatmentText

### nc:VehicleType

- **nc:VehicleColorInteriorText**

### nc:WeaponType

- **nc:WeaponUsageText**

**Comment by cdmgtri** [comment]
The Harmonization Work Group recommends the proposal above, with substitution groups created for the text elements in bold.
