### ISSUE TITLE
Use nc:OrganizationIdentification as the substitution head for all nc:OrganizationXXXIdentification elements

### ISSUE THREAD

**Issue by DonClysdale** [NIEM/NIEM-Releases#83]
Adding additional Identification elements is adding to nc:OrganizationType "sprawl". It would be cleaner to use the existing nc:OrganizationIdentification element as the substitution head for all nc:OrganizationXXXIdentification elements (i.e. add to that substitutionGroup) and remove them from nc:OrganizationType.

e.g. <xs:element name="nc:OrganizationLEIIdentification" substitutionGroup="nc:OrganizationIdentification"/>

same for:
nc:OrganizationLEIIdentification
nc:OrganizationLocalIdentification
nc:OrganizationOtherIdentification
nc:OrganizationTaxIdentification

**Comment by cdmgtri** [comment]
The Harmonization Workgroup is concerned about losing the ability to set cardinality constraints on elements that are moved to substitution groups.  See #88 for discussion on how to address sprawl in the model.
