### ISSUE TITLE
Consider ways to make large objects more manageable

### ISSUE THREAD

**Issue by cdmgtri** [NIEM/NIEM-Releases#88]
NIEM has some large objects, like nc:PersonType, that contain a lot of elements, which can sometimes make it difficult to review and find requirement matches.  The Harmonization Workgroup would like the NBAC and NTAC to discuss if there are any good ways of addressing this kind of sprawl in the model.

See issues #74, #75, and #83 for suggestions on the use of substitution groups for this purpose.  The drawback with substitution groups is that you cannot assign cardinality directly to individual substitutions.

Another idea is to add labels / tagging as model metadata to help group related elements and filter search results without actually adding new elements to the model just for grouping.

> Note that the GJXDM, the predecessor of NIEM, originally included elements like "PersonPhysicalDetails" to help group related elements in large objects.  These grouping elements were later removed because the benefits were not considered to be worth dealing with the additional structures and longer paths.

**Comment by webb** [comment]
NTAC doesn't see that a large number of properties are a problem. There are few classes in NIEM that are large, and the large number of properties is narrowed down through schema subsets. 
The NTAC sees value in instances having properties directly when possible (e.g, a flat structure). Intermediate containers or additional structure for categorizing properties introduces complexity in messages that isn't helpful; we moved away from "PersonPhysicalDetails" for good reason.
