### ISSUE TITLE
Support cardinality constraints on substitutions

### ISSUE THREAD

**Issue by cdmgtri** [NIEM/NIEM-Releases#89]
The Harmonization Workgroup would like the NTAC to consider if there is a way to support cardinality constraints on substitutions.  XML Schema supports setting cardinality on substitution group heads, but not on the substitutions directly.

**Comment by webb** [comment]
There's not a way to do it in reference schemas; cardinality for substitution is unsupported.
Subsets & profiles of the reference schemas may "inline" substitution groups, as sequences or choice compositors, but that's outside the conformance rules.
Cardinality can be handled with Schematron rules, as well.
