### ISSUE TITLE
Move code elements to code namespaces

### ISSUE THREAD

**Issue by cdmgtri** [NIEM/NIEM-Releases#90]
NIEM currently only locates code types in code namespaces.  The Harmonization Workgroup recommends moving code elements to the code namespaces as well.  

Pros:

- This would reduce the size of Core.
- This would help NIEM to scale better as more code sets are added.
- Moving code elements out of Core would make sure that they are not locked in minor releases and can be easily updated annually without the need for Core Supplements.

Cons:

- This would embed NIEM-specific semantics in code namespaces.  Code namespaces currently capture basic type information, plus code values and definitions that are taken directly from the source.  Adding elements and creating substitutions embeds NIEM semantics that do not come from the original sources.

Additional things to consider:

- New abstract elements may need to be added to support substitutions.
- Element names may need to be adjusted to remove qualifiers that are no longer necessary (e.g., nc:LocationStateUSPostalServiceCode => usps:LocationStateCode).
- Consider if additional support is needed to help users to selected between similar elements names that exist in different namespaces.
  - Adjust element definitions to include source info?
  - Make sure the namespace definitions are clear and that the SSGT UI makes this information easy to see when reviewing results.

**Comment by webb** [comment]
NTAC recommends moving only elements that use the representation pattern [as described in the NDR](https://reference.niem.gov/niem/specification/naming-and-design-rules/4.0/niem-ndr-4.0.html#section_10.7):
- Properties that need this level of flexibility should be given a type that uses the representation pattern. 
  - For example, `nc:LocationState` is already done this way, with type `nc:StateType` containing an element `nc:StateRepresentation`.
- Elements of code types should be moved into the namespace of the code type and (when possible) given names corresponding to the code type.
  - For example, element `nc:LocationStateUSPostalServiceCode` of type `usps:USStateCodeType` should be moved into the `usps` namespace and renamed to `usps:USStateCode`, substitutable for `nc:StateRepresentation`.
The NTAC does not recommend that semantic elements (with more complicated or specific meaning) be moved into code namespaces.
- For example, elements `nc:DocumentLanguageCode`, `nc:PublicServiceLanguageCode`, and `biom:DomniantSpokenLanguageCode` should not be moved into the namespace of its type, `iso_639-3:LanguageCodeType`.
  - However, an element `iso_639-3:LanguageCode` should reside in the namespace of the code type.

**Comment by cdmgtri** [comment]
**Candidate elements to move to code namespaces**

Current element | Updated element | Substitution group
--- | --- | ---
**Education** | -- | --
nc:EducationLevelBLSCode | bls:EducationLevelCode | nc:EducationLevelRepresentation
nc:EducationLevelOPMCode | opm:EducationLevelCode | nc:EducationLevelRepresentation
**Canada Post** | -- | --
nc:StateCanadaCode | can:StateCode / can:ProvinceCode | nc:StateRepresentation
nc:StreetCategory-CanadaPostCode | can:StreetCategoryCode | nc:StreetCategoryAbstract
nc:StreetPostdirectional-CanadaPostCode | can:StreetDirectionalCode | nc:StreetDirectionalRepresentation - *new / extra level*
nc:StreetPredirectional-CanadaPostCode | (see above) | (see above)
**USPS** | -- | --
nc:StateUSPSCode | usps:StateCode | nc:StateRepresentation
nc:StreetCategoryUSPSCode | usps:StreetCategoryCode | nc:StreetCategoryAbstract
nc:StreetPostdirectional-USPSCode | usps:StreetDirectionalCode | nc:StreetDirectionalRepresentation - *new / extra level*
nc:StreetPredirectional-USPSCode | (see above) | (see above)

(to be continued...)

**Comment by cdmgtri** [comment]
The Harmonization Workgroup recommends making the proposed changes.

**Comment by cdmgtri** [comment]
The OmniClass standard which we use for the facility codes labels these as "functions", not "usages" or "categories".  Updated nc:FacilityUsageType and the OCCS components accordingly.

Also replaced nc:DocumentLanguageAbstract in nc:DocumentType with nc:DocumentLanguage.
